
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.metrics.core"
    
    interface Metric
    
    interface Addable<T>
    interface Metric
    Addable <|-- AggregateMetric
    Metric <|-- AggregateMetric
    interface AggregateMetric<T>
    {
    }
    
    Metric <|-- BaseMetric
    abstract class BaseMetric<T>
    {
        --(constructors)--
        #BaseMetric()
        #BaseMetric(BaseMetric<T>)
        --
        +BaseMetric<T> description(String description)
        +BaseMetric<T> type(MetricType)
        +BaseMetric<T> unit(String unit)
        --(naming)--
        +BaseMetric<T> name(String name)
    }
    
    interface CreatedAt
    interface DoubleValued
    interface Named
    Named <|-- Metric
    CreatedAt <|-- Metric
    DoubleValued <|-- Metric
    interface Metric<T>
    {
        --
        +String description()
        +T measurement()
        +MetricType type()
        +String unit()
    }
    
    enum Metric.MetricType
    {
        COUNT
        LEVEL
        OBSERVATION
    }
    
    interface MetricsReporter
    {
        --
        +void report(Metric<?>)
    }
    
@enduml

