
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.serialization.gson.serializers.value"
    
    abstract BaseGsonSerializer
    
    BaseGsonSerializer <|-- CountGsonSerializer
    class CountGsonSerializer
    {
        --(constructors)--
        +CountGsonSerializer()
    }
    
    BaseGsonSerializer <|-- ProblemGsonSerializer
    class ProblemGsonSerializer
    {
        --(constructors)--
        +ProblemGsonSerializer()
    }
    
@enduml

