@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.test"
    
    interface ProjectTrait
    interface PackageTrait
    interface JavaTrait
    interface NamedObject
    interface LanguageTrait
    interface Repeater
    interface RegistryTrait
    
    CoreUnitTest <|-- UnitTest
    JavaTrait <|-- UnitTest
    ProjectTrait <|-- UnitTest
    PackageTrait <|-- UnitTest
    RegistryTrait <|-- UnitTest
    LanguageTrait <|-- UnitTest
    Repeater <|-- UnitTest
    NamedObject <|-- UnitTest
    class UnitTest
    {
    }
    
@enduml

