@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.resource.packages"
    
    abstract BaseRepeater
    abstract BaseReadableResource
    
    interface ResourceFolder
    interface ResourceResolver
    interface ResourceFolderResolver
    
    BaseRepeater <|-- Package
    ResourceFolder <|-- Package
    class Package
    {
        --(constructors)--
        +Package(Listener, PackagePath)
        --
        +Package child(String name)
        +Package packageContaining(Listener, Class<?> packageType)
        +Package parent()
        +PackageReference reference()
        --(collection)--
        +PropertyMap localizedProperties(Listener, Locale)
        --(parsing)--
        +Package parsePackage(Listener, Class<?> packageType, String path)
        --(path)--
        +Package packageForPath(Listener, PackagePath)
    }
    
    ResourcePath <|-- PackagePath
    class PackagePath
    {
        --
        +Class<?> packageType()
        --(checks)--
        +boolean hasPackageType()
        --(conversion)--
        +Package asPackage(Listener)
        +PackageReference asPackageReference()
        --(path)--
        +Set<PackagePath> directorySubPackages()
        +boolean isPackagePath(String path)
        +Set<PackagePath> jarSubPackages()
        +PackagePath packagePath(PackageReference)
        +PackagePath packagePath(Class<?> type, StringPath)
        +PackagePath packagePath(StringPath)
        +PackagePath packagePath(Class<?> type)
        +PackagePath parsePackagePath(Listener, String path)
        +PackagePath parsePackagePath(Listener, Class<?> type, String relativePath)
        +PackagePath withPackageType(Class<?> type)
    }
    
    BaseReadableResource <|-- PackageResource
    class PackageResource
    {
        --(constructors)--
        #PackageResource(Listener, PackagePath, ModuleResource, FileName)
        --
        +PackageResource packageResource(Listener, PackagePath, String path)
        +PackageResource packageResource(Listener, Class<?> type, String path)
        +PackageResource packageResource(Listener, ModuleResource)
        +PackageResource packageResource(Listener, PackagePath, FileName)
        +PackageResource packageResource(Listener, PackagePath, FilePath)
    }
    
    interface Repeater
    Repeater <|-- PackageTrait
    interface PackageTrait
    {
        --
        +Package packageContaining(Class<?> type)
        +PackageResource packageResource(String path)
        +Package relativePackage(String path)
        +Package thisPackage()
        --(path)--
        +PackagePath packagePath(Class<?> type)
        +PackagePath thisPackagePath()
    }
    
    interface Packaged
    {
        --
        +Package _package()
    }
    
    ResourceFolderResolver <|-- Package.Resolver
    class Package.Resolver
    {
    }
    
    ResourceResolver <|-- PackageResource.Resolver
    class PackageResource.Resolver
    {
    }
    
@enduml

