@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.conversion.core.identifier"
    
    QuantizableConverter <|-- IdentifierConverter
    class IdentifierConverter
    {
        --(constructors)--
        +IdentifierConverter(Listener)
    }
    
    QuantizableConverter <|-- IntegerIdentifierConverter
    class IntegerIdentifierConverter
    {
        --(constructors)--
        +IntegerIdentifierConverter(Listener)
    }
    
@enduml

