@startuml

    !include lexakai.theme
    
    title "Converters - Other"
    
    abstract BaseStringConverter
    
    QuantizableConverter <|-- IdentifierConverter
    class IdentifierConverter
    {
        --(constructors)--
        +IdentifierConverter(Listener)
    }
    
    QuantizableConverter <|-- IntegerIdentifierConverter
    class IntegerIdentifierConverter
    {
        --(constructors)--
        +IntegerIdentifierConverter(Listener)
    }
    
    BaseStringConverter <|-- LanguageIsoCodeConverter
    class LanguageIsoCodeConverter
    {
        --(constructors)--
        +LanguageIsoCodeConverter(Listener)
    }
    
    BaseStringConverter <|-- StringListConverter
    class StringListConverter
    {
        --(constructors)--
        +StringListConverter(Listener)
        +StringListConverter(Listener, String)
    }
    
    BaseStringConverter <|-- VersionConverter
    class VersionConverter
    {
        --(constructors)--
        +VersionConverter(Listener)
    }
    
@enduml

