@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.mixins.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramMixin
    class DiagramMixin
    {
    }
    
@enduml

