
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.application.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramApplication
    class DiagramApplication
    {
    }
    
@enduml

