@startuml

    !include lexakai.theme
    
    title "diagram-code"
    
    interface Callback<Value>
    {
        --
        +void callback(Value)
        +void onCallback(Value)
    }
    
    interface Loopable
    {
        --
        +void iteration(int iteration)
    }
    
@enduml

