
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.interfaces.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramCode
    class DiagramCode
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramCollection
    class DiagramCollection
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramComparison
    class DiagramComparison
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramFactory
    class DiagramFactory
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramFunction
    class DiagramFunction
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramIo
    class DiagramIo
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramLifeCycle
    class DiagramLifeCycle
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramLoading
    class DiagramLoading
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramMessaging
    class DiagramMessaging
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramModel
    class DiagramModel
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramNaming
    class DiagramNaming
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramNumeric
    class DiagramNumeric
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramString
    class DiagramString
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramTime
    class DiagramTime
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramValue
    class DiagramValue
    {
    }
    
@enduml

