@startuml

    !include lexakai.theme
    
    title "diagram-failure-reporter"
    
    interface Listener
    Listener <|-- FailureReporter
    interface FailureReporter
    {
        --
        +void report(Message)
        --(status)--
        +FailureReporter asserting()
        +FailureReporter logging()
        +FailureReporter none()
        +FailureReporter throwing()
    }
    
@enduml

