
@startuml

    !include lexakai.theme
    
    title "kivakit-extraction"
    
    artifact cactus_metadata
    artifact kivakit_core
    artifact kivakit_extraction
    artifact kivakit_interfaces
    artifact kivakit_internal_testing
    artifact kivakit_mixins
    artifact lexakai_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_core --> cactus_metadata
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_extraction --> kivakit_core
    kivakit_extraction --> kivakit_internal_testing
    kivakit_internal_testing --> annotations
    kivakit_internal_testing --> junit
    kivakit_internal_testing --> lexakai_annotations
    
@enduml
