@startuml

    !include lexakai.theme
    
    title "kivakit-filesystems-s3fs"
    
    artifact gson
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_conversion
    artifact kivakit_core
    artifact kivakit_filesystems_s3fs
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact kivakit_resource
    artifact kivakit_serialization_gson
    artifact kivakit_serialization_properties
    artifact kivakit_settings
    artifact kivakit_validation
    artifact lexakai_annotations
    artifact netty_reactive_streams_http
    artifact netty_reactive_streams
    artifact commons_codec
    artifact commons_logging
    artifact netty_buffer
    artifact netty_codec_http2
    artifact netty_codec
    artifact netty_common
    artifact netty_resolver
    artifact netty_transport_native_epoll
    artifact netty_transport_native_unix_common
    artifact netty_transport
    artifact junit
    artifact httpclient
    artifact hamcrest_core
    artifact annotations
    artifact reactive_streams
    artifact slf4j_api
    artifact annotations
    artifact apache_client
    artifact arns
    artifact auth
    artifact aws_core
    artifact aws_query_protocol
    artifact aws_xml_protocol
    artifact http_client_spi
    artifact json_utils
    artifact metrics_spi
    artifact netty_nio_client
    artifact profiles
    artifact protocol_core
    artifact regions
    artifact s3
    artifact sdk_core
    artifact third_party_jackson_core
    artifact utils
    artifact eventstream
    apache_client --> httpclient
    auth --> eventstream
    auth --> json_utils
    aws_xml_protocol --> aws_query_protocol
    httpclient --> commons_codec
    httpclient --> commons_logging
    json_utils --> third_party_jackson_core
    junit --> hamcrest_core
    kivakit_commandline --> kivakit_core
    kivakit_commandline --> kivakit_validation
    kivakit_core --> cactus_build_metadata
    kivakit_core --> junit
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_filesystems_s3fs --> kivakit_settings
    kivakit_filesystems_s3fs --> s3
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_resource --> kivakit_collections
    kivakit_serialization_gson --> gson
    kivakit_serialization_gson --> kivakit_conversion
    kivakit_settings --> kivakit_commandline
    kivakit_settings --> kivakit_resource
    kivakit_settings --> kivakit_serialization_gson
    kivakit_settings --> kivakit_serialization_properties
    netty_nio_client --> netty_buffer
    netty_nio_client --> netty_codec
    netty_nio_client --> netty_codec_http2
    netty_nio_client --> netty_common
    netty_nio_client --> netty_reactive_streams_http
    netty_nio_client --> netty_transport
    netty_nio_client --> netty_transport_native_epoll
    netty_reactive_streams_http --> netty_reactive_streams
    netty_transport --> netty_resolver
    netty_transport_native_epoll --> netty_transport_native_unix_common
    s3 --> annotations
    s3 --> apache_client
    s3 --> arns
    s3 --> auth
    s3 --> aws_core
    s3 --> aws_xml_protocol
    s3 --> http_client_spi
    s3 --> metrics_spi
    s3 --> netty_nio_client
    s3 --> profiles
    s3 --> protocol_core
    s3 --> regions
    s3 --> sdk_core
    s3 --> utils
    sdk_core --> reactive_streams
    sdk_core --> slf4j_api
    
@enduml
