
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.collections.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramMap
    class DiagramMap
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramSet
    class DiagramSet
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramWatcher
    class DiagramWatcher
    {
    }
    
@enduml

