
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.commandline.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramArgument
    class DiagramArgument
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramCommandLine
    class DiagramCommandLine
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramSwitch
    class DiagramSwitch
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramValidation
    class DiagramValidation
    {
    }
    
@enduml

