@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.ui.swing.theme.darcula"
    
    KivaKitTheme <|-- KivaKitDarculaTheme
    class KivaKitDarculaTheme
    {
        --(constructors)--
        +KivaKitDarculaTheme()
    }
    
@enduml

