@startuml

    !include lexakai.theme
    
    title "diagram-io"
    
    interface AutoCloseable
    AutoCloseable <|-- Closeable
    interface Closeable
    {
    }
    
    interface Flushable
    {
        --(io)--
        +void flush()
        +void flush(LengthOfTime maximumWaitTime)
    }
    
    interface Openable
    {
        --
        +void open()
    }
    
@enduml

