@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.examples.configuration.lookup"
    
    class Alien
    {
        --(constructors)--
        +Alien(Spaceship)
        --
        +void attack()
    }
    
    class AttackPlan
    {
        --(constructors)--
        #AttackPlan(AttackPlan)
        +AttackPlan()
        --(time)--
        +void waitForAttackTime()
    }
    
    class QuantumDatabase
    {
        --
        +AttackPlan retrieveAttackPlan()
    }
    
    class RegistryExample
    {
        --
        +void main(String[] arguments)
        --(lifecycle)--
        +void run()
    }
    
    class Spaceship
    {
        --(lifecycle)--
        +void startAttack()
    }
    
@enduml

