@startuml

    !include lexakai.theme
    
    title "kivakit-math"
    
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_core
    artifact kivakit_interfaces
    artifact kivakit_math
    artifact kivakit_mixins
    artifact lexakai_annotations
    artifact junit
    artifact commons_math
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_collections --> kivakit_core
    kivakit_core --> cactus_build_metadata
    kivakit_core --> junit
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_math --> commons_math
    kivakit_math --> kivakit_collections
    
@enduml
