@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.ui.desktop"
    
    Project <|-- DesktopUiProject
    class DesktopUiProject
    {
        --(constructors)--
        #DesktopUiProject()
        --
        +DesktopUiProject get()
    }
    
@enduml

