
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.examples.microservice.requests"
    
    abstract BaseMicroservletResponse
    abstract BaseMicroservletRequest
    
    BaseMicroservletRequest <|-- DivisionRequest
    class DivisionRequest
    {
        --(constructors)--
        +DivisionRequest()
        +DivisionRequest(int, int)
    }
    
    BaseMicroservletResponse <|-- DivisionRequest.DivisionResponse
    class DivisionRequest.DivisionResponse
    {
    }
    
@enduml

