
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.service.registry"
    
    StringIdentifier <|-- ClusterIdentifier
    class ClusterIdentifier
    {
        --(constructors)--
        #ClusterIdentifier()
        +ClusterIdentifier(String)
    }
    
    Scope o-- ClusterIdentifier
    Scope o-- Scope.Type
    class Scope
    {
        --(constructors)--
        #Scope()
        #Scope(Type, ClusterIdentifier)
        --
        +Scope cluster(ClusterIdentifier)
        +Scope scope(Scope.Type)
        +Set<Scope> scopes(Result<Set<Service>>)
        +Type type()
        --(checks)--
        +boolean isCluster()
        +boolean isLocal()
        --(collection)--
        +List<String> names(Result<Set<Service>>)
        --(identity)--
        +ClusterIdentifier cluster()
        --(network)--
        +boolean isNetwork()
        +Scope localhost()
        +Scope network()
    }
    
    Service o-- Application.Identifier
    Service o-- JavaVirtualMachineHealth : "health status"
    Service o-- ServiceMetadata
    Service o-- Port : "allocated port"
    Service o-- Scope : "visibility"
    Service o-- ServiceType : "provided service"
    class Service
    {
        --(constructors)--
        +Service()
        --
        +String descriptor()
        +JavaVirtualMachineHealth health()
        +Scope scope()
        --(checks)--
        +boolean isBound()
        +boolean isSame(Service that)
        +boolean isStale()
        +boolean isUnbound()
        --(identity)--
        +Application.Identifier application()
        --(network)--
        +String hostAndApplication()
        +String hostApplicationAndPort()
        +Port port()
        --(service)--
        +Service application(Application.Identifier)
        +Service health(JavaVirtualMachineHealth)
        +ServiceMetadata metadata()
        +Service metadata(ServiceMetadata)
        +Service port(Port)
        +Service renewedAt(Time renewedAt)
        +Service scope(Scope)
        +Service type(ServiceType)
        +ServiceType type()
        --(time)--
        +Time renewedAt()
    }
    
    ServiceMetadata o-- Version : "service version"
    ServiceMetadata o-- Version : "kivakit version"
    ServiceMetadata o-- EmailAddress : "contact email"
    class ServiceMetadata
    {
        --
        +String description()
        --(identity)--
        +Version kivakitVersion()
        +Version version()
        --(metadata)--
        +ServiceMetadata contactEmail(EmailAddress contactEmail)
        +ServiceMetadata description(String description)
        +ServiceMetadata kivakitVersion(Version)
        +ServiceMetadata version(Version)
        --(network)--
        +EmailAddress contactEmail()
    }
    
    interface ComponentMixin
    interface ResultTrait
    ComponentMixin <|-- ServiceRegistry
    ResultTrait <|-- ServiceRegistry
    note right of ServiceRegistry
        Use ServiceRegistryClient to register and discover services
    endnote
    -interface ServiceRegistry
    {
        --(checks)--
        +boolean isLocal()
        --(collection)--
        +Result<Boolean> addOrUpdate(Service)
        --(network)--
        +Result<Set<Host>> discoverHosts()
        +boolean isNetwork()
        --(search)--
        +Result<Set<Application.Identifier>> discoverApplications(Scope)
        --(service)--
        +Result<Service> discoverPortService(Port)
        +Result<Set<Service>> discoverServices(Application.Identifier)
        +Result<Set<Service>> discoverServices()
        +Result<Set<Service>> discoverServices(ServiceType)
        +Result<Set<Service>> discoverServices(Application.Identifier, ServiceType)
        +Result<Service> register(Service)
        +Result<Service> renew(Service)
        +ServiceRegistrySettings settings()
    }
    
    KryoTypes <|-- ServiceRegistryKryoTypes
    class ServiceRegistryKryoTypes
    {
        --(constructors)--
        +ServiceRegistryKryoTypes()
    }
    
    Project <|-- ServiceRegistryProject
    class ServiceRegistryProject
    {
    }
    
    class ServiceRegistrySettings
    {
        --(identity)--
        +Version version()
        +void version(Version)
        --(network)--
        +Port local()
        +Port network()
        +Duration portReservationExpirationTime()
        --(path)--
        +String restApiPath()
        --(service)--
        +ServiceRegistrySettings localServiceRegistryPort(int localServiceRegistryPort)
        +int localServiceRegistryPort()
        +ServiceRegistrySettings networkServiceRegistryPort(Port networkServiceRegistryPort)
        +Port networkServiceRegistryPort()
        +ServiceRegistrySettings portReservationExpirationTime(Duration portReservationExpirationTime)
        +ServiceRegistrySettings restApiPath(String restApiPath)
        +ServiceRegistrySettings serviceLeaseRenewalFrequency(Frequency serviceRenewalFrequency)
        +Frequency serviceLeaseRenewalFrequency()
        +Duration serviceRegistrationExpirationTime()
        +ServiceRegistrySettings serviceRegistrationExpirationTime(Duration registrationExpirationTime)
        +ServiceRegistrySettings serviceRegistryStoreExpirationTime(Duration serviceRegistryStoreExpirationTime)
        +Duration serviceRegistryStoreExpirationTime()
    }
    
    interface ServiceRegistryUpdater
    {
        --(messaging)--
        +void sendUpdate(Service)
    }
    
    class ServiceType
    {
        --(constructors)--
        #ServiceType()
        +ServiceType(String)
    }
    
    enum Scope.Type
    {
        CLUSTER
        LOCALHOST
        NETWORK
    }
    
@enduml

