@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.serialization.kryo.types"
    
    interface Named
    
    KryoTypes <|-- CoreKryoTypes
    class CoreKryoTypes
    {
        --(constructors)--
        +CoreKryoTypes()
    }
    
    class KryoTypeEntry
    {
        --(filesystem)--
        +KryoTypeEntry copy()
    }
    
    Named <|-- KryoTypes
    class KryoTypes
    {
        --(constructors)--
        +KryoTypes()
        --
        +void group(String name, Runnable code)
        +Set<Class<?>> registeredTypes()
        --(filesystem)--
        +KryoTypes deepCopy()
        --(functional)--
        +KryoTypes mergedWith(KryoTypes that)
        --(identity)--
        +int identifier(Class<?> type)
        --(lookup)--
        +KryoTypes register(Class<?> type)
        +KryoTypes register(Class<?> type, Serializer<?>)
        +KryoTypes registerDynamic(Class<?> type, Serializer<?>, int identifier)
        +void registerWith(Kryo)
    }
    
    KryoTypes <|-- ResourceKryoTypes
    class ResourceKryoTypes
    {
        --(constructors)--
        +ResourceKryoTypes()
    }
    
@enduml

