
@startuml

    !include lexakai.theme
    
    title "diagram-function"
    
    interface Predicate<Value>
    Predicate <|-- BooleanFunction
    interface BooleanFunction<Value>
    {
        --(checks)--
        +boolean isFalse(Value)
        +boolean isTrue(Value)
    }
    
@enduml

