@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.configuration.settings.stores.memory"
    
    abstract BaseSettingsStore
    
    BaseSettingsStore <|-- MemorySettingsStore
    class MemorySettingsStore
    {
    }
    
@enduml

