@startuml

    !include lexakai.theme
    
    title "kivakit-merged-prometheus"
    
    artifact kivakit_merged_prometheus
    artifact simpleclient
    artifact simpleclient_common
    artifact simpleclient_hotspot
    artifact simpleclient_httpserver
    artifact simpleclient_servlet
    artifact simpleclient_servlet_common
    artifact simpleclient_tracer_common
    artifact simpleclient_tracer_otel
    artifact simpleclient_tracer_otel_agent
    kivakit_merged_prometheus --> simpleclient
    kivakit_merged_prometheus --> simpleclient_hotspot
    kivakit_merged_prometheus --> simpleclient_httpserver
    kivakit_merged_prometheus --> simpleclient_servlet
    simpleclient --> simpleclient_tracer_otel
    simpleclient --> simpleclient_tracer_otel_agent
    simpleclient_httpserver --> simpleclient_common
    simpleclient_servlet --> simpleclient_servlet_common
    simpleclient_tracer_otel --> simpleclient_tracer_common
    
@enduml
