
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.security.internal.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramSecurity
    class DiagramSecurity
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramSecurityDigest
    class DiagramSecurityDigest
    {
    }
    
@enduml

