@startuml

    !include lexakai.theme
    
    title "kivakit-mixins"
    
    artifact cactus_metadata
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact lexakai_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_mixins --> junit
    kivakit_mixins --> kivakit_interfaces
    lexakai_annotations --> cactus_metadata
    
@enduml
