
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.data.formats.csv.internal.lexakai"
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramCsv
    interface DiagramCsv
    {
    }
    
@enduml

