
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.data.formats.csv"
    
    abstract BaseIterator
    abstract BaseRepeater
    
    interface RepeaterMixin
    interface Closeable
    interface PropertyValue
    interface PropertyFilter
    
    Name <|-- CsvColumn
    class CsvColumn<Type>
    {
        --(constructors)--
        #CsvColumn(String, StringConverter<Type>)
        --
        +CsvColumn<T> csvColumn(String name, StringConverter<T>)
        +CsvColumn<T> csvColumn(String name)
        +CsvSchema schema()
        --(collection)--
        +ObjectList<Type> asType(String text, BaseStringConverter<Type>)
        --(conversion)--
        +String asString(Type value, StringConverter<Type>)
        +String asString(Type value)
        +Type asType(String text, StringConverter<Type>)
        +Type asType(String text)
    }
    
    BaseRepeater <|-- CsvLine
    PropertyValue <|-- CsvLine
    class CsvLine
    {
        --(constructors)--
        +CsvLine(CsvSchema, char)
        --
        +T get(CsvColumn<T>)
        +String get(int index)
        +T get(CsvColumn<T>, StringConverter<T>)
        +int lineNumber()
        +CsvSchema schema()
        +void set(CsvColumn<T>, T value)
        +void set(int index, String value)
        +String string(CsvColumn<?>)
        #char delimiter()
        --(collection)--
        +boolean add(String value)
        +StringList columns()
        +ObjectList<T> get(CsvColumn<T>, BaseStringConverter<T>)
        --(functional)--
        +T populatedObject(Class<T> type)
    }
    
    PropertyFilter <|-- CsvPropertyFilter
    class CsvPropertyFilter
    {
        --(constructors)--
        +CsvPropertyFilter(CsvSchema)
    }
    
    BaseIterator <|-- CsvReader
    RepeaterMixin <|-- CsvReader
    Closeable <|-- CsvReader
    CsvReader --> CsvLine : "reads"
    CsvReader o-- CsvSchema : "uses"
    class CsvReader
    {
        --(constructors)--
        +CsvReader(Resource, CsvSchema, char, ProgressReporter)
        --
        +void delimiter(char delimiter)
        +int lineNumber()
        +CsvSchema schema()
        #void processLeadingSpaces(LookAheadReader in, StringBuffer)
        #void skipLine(LookAheadReader in)
        --(collection)--
        +Iterable<CsvLine> lines()
        --(iteration)--
        #String extractNextColumn(LookAheadReader in)
        --(read)--
        +CsvReader quote(char quote)
        +CsvReader skipLines(int numberOfLinesToSkip)
        +CsvReader unquoted()
        #void readColumn(LookAheadReader in, StringBuffer)
        #void readQuotedColumn(LookAheadReader in, StringBuffer)
    }
    
    BaseRepeater <|-- CsvSchema
    CsvSchema "1" o-- "*" CsvColumn
    class CsvSchema
    {
        --(constructors)--
        #CsvSchema(CsvColumn<?>)
        --
        +CsvSchema csvSchema(CsvColumn<?>... columns)
        --(collection)--
        +CsvSchema add(CsvColumn<?>)
        +CsvSchema addAll(List<? extends CsvColumn<?>> columns)
        +CsvSchema addAll(CsvColumn<?>... columns)
        +boolean contains(CsvColumn<?>)
        --(naming)--
        +CsvColumn<?> columnForName(String name)
    }
    
    BaseRepeater <|-- CsvWriter
    Closeable <|-- CsvWriter
    CsvWriter --> CsvLine : "writes"
    CsvWriter o-- CsvSchema : "uses"
    class CsvWriter
    {
        --(constructors)--
        +CsvWriter(PrintWriter, ProgressReporter, CsvSchema)
        --
        +CsvSchema schema()
        --(write)--
        +void write(CsvLine)
        +void writeComment(String comment)
    }
    
    CsvReader <|-- UnquotedCsvReader
    class UnquotedCsvReader
    {
        --(constructors)--
        +UnquotedCsvReader(Resource, CsvSchema, char, ProgressReporter)
    }
    
@enduml

