@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.logs.client.view.panels.table"
    
    abstract AbstractTableModel
    
    DefaultTableCellRenderer <|-- TableCellRenderer
    class TableCellRenderer
    {
    }
    
    RowFilter <|-- TableFilter
    class TableFilter
    {
    }
    
    AbstractTableModel <|-- TableModel
    class TableModel
    {
        --(constructors)--
        +TableModel(ClientLogPanel, int)
        --
        +LogEntry row(int which)
        --(collection)--
        +void addRows(List<LogEntry> toAdd)
        +void clear()
    }
    
    KivaKitPanel <|-- TablePanel
    class TablePanel
    {
        --(constructors)--
        +TablePanel(ClientLogPanel)
        --
        +void scroll()
        +void update()
        --(collection)--
        +void add(LogEntry)
        +void addAll(List<LogEntry> entries)
        +void clear()
        +Count rows()
        --(filtering)--
        +void filter(String searchText, String thread, String context, String messageType)
    }
    
@enduml

