@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.serialization.kryo.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramKryo
    class DiagramKryo
    {
    }
    
@enduml

