@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.web.swagger"
    
    abstract BaseJettyServletPlugin
    abstract BaseJettyResourcePlugin
    
    HttpServlet <|-- SwaggerIndexJettyResourcePlugin.IndexServlet
    class SwaggerIndexJettyResourcePlugin.IndexServlet
    {
    }
    
    Project <|-- JettySwaggerProject
    class JettySwaggerProject
    {
        --(constructors)--
        #JettySwaggerProject()
        --
        +JettySwaggerProject get()
    }
    
    AssetsJettyResourcePlugin <|-- SwaggerAssetsJettyResourcePlugin
    class SwaggerAssetsJettyResourcePlugin
    {
        --(constructors)--
        +SwaggerAssetsJettyResourcePlugin()
    }
    
    BaseJettyResourcePlugin <|-- SwaggerIndexJettyResourcePlugin
    class SwaggerIndexJettyResourcePlugin
    {
        --(constructors)--
        +SwaggerIndexJettyResourcePlugin(int)
    }
    
    BaseJettyServletPlugin <|-- SwaggerJettyServletPlugin
    class SwaggerJettyServletPlugin
    {
        --(constructors)--
        +SwaggerJettyServletPlugin(Application)
    }
    
    BaseJettyResourcePlugin <|-- SwaggerWebJarJettyResourcePlugin
    class SwaggerWebJarJettyResourcePlugin
    {
        --(constructors)--
        +SwaggerWebJarJettyResourcePlugin(Class<?>)
    }
    
@enduml

