@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.protocols.lambda"
    
    interface RequestHandler
    interface ComponentMixin
    
    RequestHandler <|-- LambdaRequestHandler
    ComponentMixin <|-- LambdaRequestHandler
    class LambdaRequestHandler
    {
    }
    
@enduml

