
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.network.core.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramAuthentication
    class DiagramAuthentication
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramNetworkLocation
    class DiagramNetworkLocation
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPort
    class DiagramPort
    {
    }
    
@enduml

