@startuml

    !include lexakai.theme
    
    title "kivakit-web-wicket"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact openjson
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_component
    artifact kivakit_configuration
    artifact kivakit_kernel
    artifact kivakit_network_core
    artifact kivakit_network_http
    artifact kivakit_resource
    artifact kivakit_security
    artifact kivakit_serialization_core
    artifact kivakit_serialization_kryo
    artifact kivakit_test
    artifact kivakit_web_jetty
    artifact kivakit_web_wicket
    artifact lexakai_annotations
    artifact commons_codec
    artifact commons_fileupload
    artifact commons_io
    artifact commons_logging
    artifact kryo_serializers
    artifact swagger_annotations
    artifact jakarta_activation_api
    artifact jakarta_servlet_api
    artifact javax_servlet_api
    artifact junit
    artifact commons_collections4
    artifact httpclient
    artifact httpcore
    artifact wicket_core
    artifact wicket_extensions
    artifact wicket_request
    artifact wicket_util
    artifact apiguardian_api
    artifact jdk_serializable_functional
    artifact jetty_http
    artifact jetty_io
    artifact jetty_security
    artifact jetty_server
    artifact jetty_servlet
    artifact jetty_util_ajax
    artifact jetty_util
    artifact jetty_webapp
    artifact jetty_xml
    artifact hamcrest_core
    artifact annotations
    artifact junit_jupiter_api
    artifact junit_jupiter_engine
    artifact junit_jupiter_params
    artifact junit_jupiter
    artifact junit_platform_commons
    artifact junit_platform_engine
    artifact objenesis
    artifact opentest4j
    artifact asm
    artifact slf4j_api
    httpclient --> commons_codec
    httpclient --> commons_logging
    httpclient --> httpcore
    jetty_http --> jetty_util
    jetty_server --> jetty_http
    jetty_server --> jetty_io
    jetty_servlet --> jetty_security
    jetty_servlet --> jetty_util_ajax
    jetty_webapp --> jetty_servlet
    jetty_webapp --> jetty_xml
    junit --> hamcrest_core
    junit_jupiter --> junit_jupiter_api
    junit_jupiter --> junit_jupiter_params
    junit_jupiter_api --> opentest4j
    junit_jupiter_engine --> junit_platform_engine
    kivakit_collections --> kivakit_serialization_kryo
    kivakit_component --> kivakit_configuration
    kivakit_configuration --> kivakit_resource
    kivakit_configuration --> kivakit_test
    kivakit_kernel --> annotations
    kivakit_kernel --> cactus_build_metadata
    kivakit_kernel --> jackson_annotations
    kivakit_kernel --> lexakai_annotations
    kivakit_kernel --> swagger_annotations
    kivakit_network_core --> kivakit_security
    kivakit_network_http --> httpclient
    kivakit_network_http --> kivakit_network_core
    kivakit_resource --> kivakit_collections
    kivakit_resource --> kivakit_commandline
    kivakit_resource --> kivakit_serialization_core
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kivakit_test --> junit
    kivakit_test --> kivakit_kernel
    kivakit_web_jetty --> jakarta_activation_api
    kivakit_web_jetty --> javax_servlet_api
    kivakit_web_jetty --> jetty_server
    kivakit_web_jetty --> jetty_webapp
    kivakit_web_jetty --> kivakit_network_http
    kivakit_web_wicket --> apiguardian_api
    kivakit_web_wicket --> jakarta_servlet_api
    kivakit_web_wicket --> jdk_serializable_functional
    kivakit_web_wicket --> junit_jupiter
    kivakit_web_wicket --> junit_jupiter_engine
    kivakit_web_wicket --> junit_platform_commons
    kivakit_web_wicket --> kivakit_component
    kivakit_web_wicket --> kivakit_web_jetty
    kivakit_web_wicket --> wicket_core
    kivakit_web_wicket --> wicket_extensions
    kivakit_web_wicket --> wicket_request
    kivakit_web_wicket --> wicket_util
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    wicket_core --> openjson
    wicket_core --> slf4j_api
    wicket_util --> commons_collections4
    wicket_util --> commons_fileupload
    wicket_util --> commons_io
    
@enduml
