@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.filesystems.github.project"
    
    Project <|-- FileSystemsGitHubProject
    class FileSystemsGitHubProject
    {
        --(constructors)--
        #FileSystemsGitHubProject()
        --(filesystem)--
        +FileSystemsGitHubProject get()
    }
    
@enduml

