
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core.version"
    
    interface Versioned
    interface NamedObject
    
    enum Release
    {
        ALPHA
        BETA
        FINAL
        M1
        M2
        M3
        M4
        M5
        M6
        M7
        M8
        M9
        RC
        RELEASE
    }
    
    class Version
    {
        --(constructors)--
        #Version()
        #Version(int, int, int, Release, boolean)
        --
        +int major()
        +int minor()
        +int patch()
        +Release release()
        --(checks)--
        +boolean hasPatch()
        +boolean hasRelease()
        +boolean isNewerThan(Version that)
        +boolean isNewerThanOrEqualTo(Version that)
        +boolean isOlderThan(Version that)
        +boolean isOlderThanOrEqualTo(Version that)
        +boolean isSnapshot()
        --(identity)--
        +boolean hasMinorVersion()
        +Version newer(Version that)
        +Version of(int major)
        +Version of(int major, int minor, int patch)
        +Version of(int major, int minor)
        +Version of(int major, int minor, int patch, Release, boolean snapshot)
        +Version older(Version that)
        +Version parseVersion(String text)
        +Version parseVersion(Listener, String text)
        +Version version(String text)
        +Version withoutPatch()
        +Version withoutRelease()
        +Version withoutSnapshot()
        --(primitive)--
        +double asDouble()
    }
    
    interface Versioned
    {
        --(identity)--
        +boolean hasVersion()
        +Version version()
    }
    
    NamedObject <|-- VersionedObject
    Versioned <|-- VersionedObject
    class VersionedObject<T>
    {
        --(constructors)--
        +VersionedObject()
        +VersionedObject(T, Version)
        --
        +T object()
    }
    
@enduml

