
@startuml

    !include lexakai.theme
    
    title "diagram-language"
    
    abstract BaseRepeater
    
    interface Sized
    interface Comparable
    
    Sized <|-- Differences
    Differences o-- StringList
    class Differences
    {
        --
        +boolean compare(String description, Iterable<T>, Iterable<T>)
        +boolean compare(String description, T a, T b)
        --(checks)--
        +boolean isDifferent()
        +boolean isIdentical()
        --(collection)--
        +void add(String description)
        +void add(Differences that)
    }
    
    BaseRepeater <|-- JavaVirtualMachine
    JavaVirtualMachine o-- Instrumentation
    JavaVirtualMachine o-- JavaVirtualMachineHealth
    class JavaVirtualMachine
    {
        --
        +void agentmain(String arguments, Instrumentation)
        +boolean assertionsEnabled()
        +void dumpHeap(Path)
        +JavaVirtualMachineHealth health()
        +boolean instrument()
        +void instrumentation(Instrumentation)
        +void invalidateProperties()
        +JavaVirtualMachine local()
        +void main(String[] args)
        +void premain(String arguments, Instrumentation)
        +ThreadSnapshot threadSnapshot()
        --(checks)--
        +boolean isInstrumented()
        --(collection)--
        +Count processors()
        +VariableMap<String> properties()
        +VariableMap<String> variables()
        --(primitive)--
        +Bytes freeMemory()
        +Bytes maximumMemory()
        +Bytes sizeOf(Object)
        +Bytes sizeOfObjectGraph(Object, String prefix, Bytes minimumSizeToDebugTrace)
        +Bytes sizeOfObjectGraph(Object)
        +Bytes sizeOfPrimitive(Object value)
        +Bytes sizeOfPrimitiveType(Class<?> type)
        +Bytes totalMemory()
        +Bytes traceSizeChange(Listener, String operation, Object root, Bytes minimumDebugTraceSize, Runnable)
        +Bytes usedMemory()
    }
    
    class JavaVirtualMachineHealth
    {
        --
        +double cpuUse()
        +void logEntry(LogEntry)
        +double memoryUse()
        +ThreadSnapshot threadSnapshot()
        +JavaVirtualMachineHealth update()
        --(collection)--
        +Count count(String messageType)
        +Count processors()
        --(primitive)--
        +Bytes freeMemory()
        +Bytes maximumMemory()
        +Map<String,Integer> messageType()
        +Bytes totalMemory()
        +Bytes usedMemory()
        --(time)--
        +Duration elapsed()
        +Duration elapsedCpuTime()
        +Duration upTime()
    }
    
    class Lists
    {
        --(collection)--
        +ArrayList<T> arrayList(T... objects)
    }
    
    Comparable <|-- ShutdownHook
    class ShutdownHook
    {
        --(lookup)--
        +void register(String name, Duration maximumWait, Runnable code)
        +void register(String name, Runnable code)
        +void register(String name, Order, Duration maximumWait, Runnable code)
        +void register(String name, Order, Runnable code)
    }
    
    class Streams
    {
        --
        +Stream<T> parallelStream(Iterable<T>)
        +Stream<T> stream(Processing, Iterable<T>)
        +Stream<T> stream(Iterable<T>)
    }
    
@enduml

