@startuml

    !include lexakai.theme
    
    title "kivakit-filesystems-github"
    
    artifact kryo
    artifact minlog
    artifact reflectasm
    artifact jackson_annotations
    artifact jackson_core
    artifact jackson_databind
    artifact gson
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_component
    artifact kivakit_configuration
    artifact kivakit_filesystems_github
    artifact kivakit_kernel
    artifact kivakit_resource
    artifact kivakit_serialization_core
    artifact kivakit_serialization_json
    artifact kivakit_serialization_kryo
    artifact kivakit_test
    artifact lexakai_annotations
    artifact commons_io
    artifact kryo_serializers
    artifact swagger_annotations
    artifact junit
    artifact commons_lang3
    artifact hamcrest_core
    artifact annotations
    artifact github_api
    artifact objenesis
    artifact asm
    github_api --> commons_io
    github_api --> commons_lang3
    github_api --> jackson_databind
    jackson_databind --> jackson_core
    junit --> hamcrest_core
    kivakit_collections --> kivakit_serialization_kryo
    kivakit_component --> kivakit_configuration
    kivakit_configuration --> kivakit_resource
    kivakit_configuration --> kivakit_serialization_json
    kivakit_filesystems_github --> github_api
    kivakit_filesystems_github --> kivakit_component
    kivakit_filesystems_github --> kivakit_test
    kivakit_kernel --> annotations
    kivakit_kernel --> cactus_build_metadata
    kivakit_kernel --> jackson_annotations
    kivakit_kernel --> lexakai_annotations
    kivakit_kernel --> swagger_annotations
    kivakit_resource --> kivakit_collections
    kivakit_resource --> kivakit_commandline
    kivakit_resource --> kivakit_serialization_core
    kivakit_serialization_json --> gson
    kivakit_serialization_kryo --> kryo
    kivakit_serialization_kryo --> kryo_serializers
    kivakit_test --> junit
    kivakit_test --> kivakit_kernel
    kryo --> minlog
    kryo --> objenesis
    kryo --> reflectasm
    reflectasm --> asm
    
@enduml
