
@startuml

    !include lexakai.theme
    
    title "Applications"
    
    abstract BaseComponent
    
    interface Named
    interface ProjectTrait
    interface PackageTrait
    interface ApplicationMetadataTrait
    interface SettingsTrait
    interface TryTrait
    
    BaseComponent <|-- Application
    Named <|-- Application
    PackageTrait <|-- Application
    ProjectTrait <|-- Application
    SettingsTrait <|-- Application
    ApplicationMetadataTrait <|-- Application
    TryTrait <|-- Application
    Application --> CommandLine : "parses arguments into"
    Application --> Application.Identifier : "identified by"
    Application o-- CommandLine
    Application "1" o-- "*" Project : "initializes and uses"
    abstract class Application
    {
        --(constructors)--
        #Application()
        --
        +Application application()
        +LifecyclePhase phase()
        +Set<Project> projects()
        +void ready()
        #void invoke(InvocationScope, Runnable code)
        #T invoke(InvocationScope, Code<T>)
        #void onInitialized()
        #void onInitializing()
        #ObjectSet<StartupOption> startupOptions()
        --(building)--
        +Build build()
        --(collection)--
        +Application addProject(Class<? extends Project>)
        +PropertyMap localizedProperties(Locale, LocaleLanguage)
        +PropertyMap localizedProperties(Locale)
        +PropertyMap properties()
        #void onAddProjects()
        --(command line parsing)--
        +T argument(ArgumentParser<T>)
        +T argument(int index, ArgumentParser<T>)
        +ArgumentValueList argumentList()
        +ObjectList<T> arguments(ArgumentParser<T>)
        +CommandLine commandLine()
        +T get(SwitchParser<T>, T defaultValue)
        +T get(SwitchParser<T>)
        +boolean has(SwitchParser<T>)
        +void parseCommandLine(String[] arguments)
        #ObjectList<ArgumentParser<?>> argumentParsers()
        #boolean ignoreDeploymentSwitch()
        #void onCommandLineParsed()
        #ObjectSet<SwitchParser<?>> switchParsers()
        --(factory)--
        #Project newProject()
        --(identity)--
        +Identifier identifier()
        --(lifecycle)--
        +void exit(String message, Object... arguments)
        +Result<ApplicationExit> run(Class<T> applicationType, String[] arguments)
        +Result<ApplicationExit> run(Listener, Class<T> applicationType, String[] arguments)
        +Result<ApplicationExit> run(String[] arguments)
        #void onInitialize()
        #void onProjectsInitialize()
        #void onRun()
        #void onSerializationInitialize()
        --(lookup)--
        #void onRegisterObjectSerializers()
        --(messaging)--
        +String startupInformation(String title)
        --(thread)--
        +void waitForReady()
    }
    
    class Application.Identifier
    {
        --(constructors)--
        #Identifier()
        +Identifier(String)
    }
    
    Application <|-- Server
    abstract class Server
    {
    }
    
@enduml

