@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.interfaces.comparison.matchers"
    
    interface Matcher
    
    Matcher <|-- Anything
    class Anything<T>
    {
    }
    
    Matcher <|-- Nothing
    class Nothing<T>
    {
    }
    
    Matcher <|-- PatternMatcher
    class PatternMatcher
    {
        --(constructors)--
        +PatternMatcher(Pattern)
    }
    
@enduml

