@startuml

    !include lexakai.theme
    
    title "kivakit-interfaces"
    
    artifact cactus_metadata
    artifact kivakit_interfaces
    artifact lexakai_annotations
    artifact annotations
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    lexakai_annotations --> cactus_metadata
    
@enduml
