
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.security.internal.lexakai"
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramSecurity
    interface DiagramSecurity
    {
    }
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramSecurityDigest
    interface DiagramSecurityDigest
    {
    }
    
@enduml

