
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.ui.desktop.graphics.drawing.style"
    
    abstract BaseStringConverter
    
    interface Iterator
    
    class Color
    {
        --
        +T applyAsSelectionBackground(T component)
        +T applyAsSelectionForeground(T component)
        --(conversion)--
        +ColorUIResource asColorUiResource()
        +String asHexString()
        +String asHexStringWithAlpha()
        --(functional)--
        +Color withAlpha(int alpha)
    }
    
    BaseStringConverter <|-- Color.ColorConverter
    class Color.ColorConverter
    {
        --(constructors)--
        +ColorConverter(Listener)
    }
    
    class Fonts
    {
        --
        +Font component(int size)
        --(functional)--
        +Font fixedWidth(int style, int size)
    }
    
    Iterator <|-- Rainbow
    class Rainbow
    {
    }
    
    class Stroke
    {
        --(constructors)--
        #Stroke()
        #Stroke(Stroke)
        #Stroke(java.awt.Stroke)
        --
        +void apply(Graphics2D)
        +Stroke defaultStroke()
        +Stroke scale(double scaleFactor)
        +Stroke scale(Percent scaleFactor)
        +Stroke stroke()
        +Stroke stroke(java.awt.Stroke)
        +DrawingWidth width()
        #java.awt.Stroke awtStroke()
        --(filesystem)--
        +Stroke copy()
        --(functional)--
        +Shape stroked(Shape)
        +Stroke withCap(int cap)
        +Stroke withDash(float[] dash)
        +Stroke withDashPhase(float dash)
        +Stroke withJoin(int join)
        +Stroke withMiterLimit(int miterLimit)
        +Stroke withWidth(DrawingWidth)
    }
    
    class Style
    {
        --(constructors)--
        #Style()
        --
        +Style apply(Component)
        +Style applyColors(Component)
        +Style applyText(Component)
        +Style applyTextColor(Component)
        +Style applyTextFont(Component)
        +Style applyToSelectionStyle(JList<?> component)
        +Style applyToSelectionStyle(JTable component)
        +Style applyToSelectionStyle(JTextComponent)
        +Style create()
        +Color drawColor()
        +Stroke drawStroke()
        +Color fillColor()
        +Stroke fillStroke()
        +Shape shape(Shape)
        +Color textColor()
        +Font textFont()
        +Style translucent()
        +Style transparent()
        --(functional)--
        +Style darkened(Percent)
        +Style darkened()
        +Style lightened(Percent)
        +Style lightened()
        +Style withAlpha(int alpha)
        +Style withDrawColor(Color)
        +Style withDrawStroke(Stroke)
        +Style withFillColor(Color fill)
        +Style withFillStroke(Stroke)
        +Style withTextColor(Color text)
        +Style withTextFont(Font)
        +Style withTextFontSize(int size)
    }
    
@enduml

