
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.data.compression.codecs.huffman"
    
    interface Codec
    interface StringFormattable
    
    StringFormattable <|-- FastHuffmanDecoder.Table.Entry
    class FastHuffmanDecoder.Table.Entry<Symbol>
    {
        --(constructors)--
        #Entry()
    }
    
    class FastHuffmanDecoder<Symbol>
    {
        --(constructors)--
        +FastHuffmanDecoder(HuffmanCodec<Symbol>)
        --
        +void decode(ByteList input, SymbolConsumer<Symbol>)
    }
    
    Codec <|-- HuffmanCodec
    class HuffmanCodec<Symbol>
    {
        --(constructors)--
        #HuffmanCodec()
        --
        +Code code(Symbol value)
        +Set<CodedSymbol<Symbol>> codedSymbols()
        +CodedSymbol<Symbol> decode(BitReader)
        +CodedSymbol<Symbol> escape()
        +HuffmanCodec<Symbol> huffmanCodec(Symbols<Symbol>, Maximum bits)
        --(collection)--
        +PropertyMap asProperties(StringConverter<Symbol>)
    }
    
    StringFormattable <|-- FastHuffmanDecoder.Table
    class FastHuffmanDecoder.Table<Symbol>
    {
        --(constructors)--
        #Table()
    }
    
@enduml

