@startuml

    !include lexakai.theme
    
    title "kivakit-merged-grpc"
    
    artifact kivakit_merged_grpc
    artifact grpc_api
    artifact grpc_context
    artifact grpc_core
    artifact grpc_netty
    artifact grpc_protobuf_lite
    artifact grpc_protobuf
    artifact grpc_stub
    artifact netty_all
    kivakit_merged_grpc --> grpc_api
    kivakit_merged_grpc --> grpc_context
    kivakit_merged_grpc --> grpc_core
    kivakit_merged_grpc --> grpc_netty
    kivakit_merged_grpc --> grpc_protobuf
    kivakit_merged_grpc --> grpc_protobuf_lite
    kivakit_merged_grpc --> grpc_stub
    kivakit_merged_grpc --> netty_all
    
@enduml
