
@startuml

    !include lexakai.theme
    
    title "Applications"
    
    abstract BaseComponent
    
    interface Named
    interface ApplicationMetadata
    
    BaseComponent <|-- Application
    Named <|-- Application
    ApplicationMetadata <|-- Application
    Application --> CommandLine : "parses arguments into"
    Application --> Application.Identifier : "identified by"
    Application o-- CommandLine
    Application "1" o-- "*" Project : "initializes and uses"
    abstract class Application
    {
        --(constructors)--
        #Application()
        --
        +Application get()
        +Set<Project> projects()
        +void ready()
        #boolean ignoreDeployments()
        #ObjectSet<StartUp.Option> startupOptions()
        --(building)--
        +Build build()
        --(collection)--
        +Application addProject(Class<? extends Project>)
        +PropertyMap localizedProperties(Locale)
        +PropertyMap properties()
        --(command line parsing)--
        +T argument(int index, ArgumentParser<T>)
        +T argument(ArgumentParser<T>)
        +ArgumentList argumentList()
        +ObjectList<T> arguments(ArgumentParser<T>)
        +CommandLine commandLine()
        +T get(SwitchParser<T>, T defaultValue)
        +T get(SwitchParser<T>)
        +boolean has(SwitchParser<T>)
        #List<ArgumentParser<?>> argumentParsers()
        #ObjectSet<SwitchParser<?>> switchParsers()
        --(factory)--
        #Project newProject()
        --(identity)--
        +Identifier identifier()
        +Version version()
        --(lifecycle)--
        +void exit(String message, Object... arguments)
        +void run(String[] arguments)
        #void onRun()
        #void onSerializationInitialize()
        --(lookup)--
        #void onRegisterObjectSerializers()
        --(messaging)--
        +String startupInformation(String title)
        --(thread)--
        +void waitForReady()
    }
    
    class Application.Identifier
    {
        --(constructors)--
        #Identifier()
        +Identifier(String)
    }
    
    Application <|-- Server
    abstract class Server
    {
    }
    
@enduml

