@startuml

    !include lexakai.theme
    
    title "Configuration and Deployment"
    
    abstract BaseRepeater
    
    interface Named
    interface Iterable
    interface SettingsTrait
    
    Settings <|-- Deployment
    Named <|-- Deployment
    class Deployment
    {
        --(constructors)--
        +Deployment(String, String)
        --
        +String description()
        --(configuration)--
        +Deployment addDeployment(Deployment)
        +SwitchParser.Builder<Deployment> deploymentSwitchParser(Listener, DeploymentSet, String switchName)
    }
    
    BaseRepeater <|-- DeploymentSet
    DeploymentSet "1" o-- "*" Deployment
    class DeploymentSet
    {
        --(constructors)--
        #DeploymentSet()
        --
        +void install(String name)
        --(collection)--
        +boolean isEmpty()
        +int size()
        --(command line parsing)--
        +SwitchParser.Builder<Deployment> switchParser(String name)
        --(configuration)--
        +void add(Deployment)
        +void addAll(Collection<Deployment> deployments)
        +DeploymentSet addDeploymentsIn(Package package_)
        +DeploymentSet addDeploymentsIn(Class<?> relativeTo, String path)
        +DeploymentSet addDeploymentsIn(PackagePath)
        +DeploymentSet addDeploymentsIn(Folder parent)
        +Deployment deployment(String name)
        +Set<Deployment> deployments()
        +DeploymentSet load(Listener, Class<?> relativeTo)
        +DeploymentSet of(Deployment, Deployment... more)
    }
    
    class InstanceIdentifier
    {
        --(constructors)--
        #InstanceIdentifier(String)
        --(identity)--
        +InstanceIdentifier instanceIdentifier(Enum<?> value)
        +InstanceIdentifier instanceIdentifier(Class<?> value)
        +InstanceIdentifier instanceIdentifier(String value)
    }
    
    BaseRepeater <|-- Settings
    SettingsTrait <|-- Settings
    Named <|-- Settings
    Iterable <|-- Settings
    class Settings
    {
        --
        +Settings install()
        +Settings of(Object)
        --(collection)--
        +void clear()
    }
    
    Settings <|-- SettingsFolder
    class SettingsFolder
    {
        --(constructors)--
        #SettingsFolder(Folder)
        --(filesystem)--
        +SettingsFolder of(Folder)
    }
    
    Settings <|-- SettingsPackage
    class SettingsPackage
    {
        --(constructors)--
        #SettingsPackage(PackagePath)
        --
        +SettingsPackage of(PackagePath)
        +SettingsPackage of(Package _package)
    }
    
@enduml

