@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.metrics.core.scalar"
    
    abstract BaseMetric
    
    BaseMetric <|-- DoubleMetric
    class DoubleMetric
    {
        --(constructors)--
        +DoubleMetric()
        +DoubleMetric(BaseMetric<Double>)
        +DoubleMetric(double)
        --(primitive)--
        +DoubleMetric withMeasurement(double quantum)
    }
    
    BaseMetric <|-- QuantumMetric
    class QuantumMetric<T>
    {
        --(constructors)--
        +QuantumMetric()
        +QuantumMetric(QuantumMetric<T>)
        --(functional)--
        +QuantumMetric<T> withMeasurement(T measurement)
    }
    
@enduml

