@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.security"
    
    Project <|-- SecurityProject
    class SecurityProject
    {
        --(constructors)--
        #SecurityProject()
        --
        +SecurityProject get()
    }
    
@enduml

