@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.extraction.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramExtraction
    class DiagramExtraction
    {
    }
    
@enduml

