@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.web.wicket"
    
    abstract BaseJettyFilterPlugin
    
    FilterHolder <|-- JettyWicketFilterHolder
    class JettyWicketFilterHolder
    {
        --(constructors)--
        +JettyWicketFilterHolder(Class<? extends WebApplication>)
        +JettyWicketFilterHolder(WebApplication)
    }
    
    Project <|-- JettyWicketProject
    class JettyWicketProject
    {
        --(constructors)--
        #JettyWicketProject()
        --
        +JettyWicketProject get()
    }
    
    BaseJettyFilterPlugin <|-- WicketJettyFilterPlugin
    class WicketJettyFilterPlugin
    {
        --(constructors)--
        +WicketJettyFilterPlugin(Class<? extends WebApplication>)
        +WicketJettyFilterPlugin(WebApplication)
    }
    
@enduml

