@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.service.registry.serialization"
    
    abstract BaseGsonFactorySource
    
    BaseGsonFactorySource <|-- ServiceRegistryGsonFactorySource
    class ServiceRegistryGsonFactorySource
    {
    }
    
    JerseyGsonSerializer <|-- ServiceRegistryJerseySerializer
    class ServiceRegistryJerseySerializer<T>
    {
        --(constructors)--
        +ServiceRegistryJerseySerializer(Listener)
    }
    
@enduml

