@startuml

    !include lexakai.theme
    
    title "kivakit-validation"
    
    artifact cactus_build_metadata
    artifact kivakit_core
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact kivakit_validation
    artifact lexakai_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_core --> cactus_build_metadata
    kivakit_core --> junit
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_validation --> kivakit_core
    
@enduml
