
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core"
    
    abstract BaseKivaKitProject
    
    Project <|-- BaseKivaKitProject
    abstract class BaseKivaKitProject
    {
    }
    
    BaseKivaKitProject <|-- KivaKit
    class KivaKit
    {
        --
        +Logger globalLogger()
        +Logger globalLogger(Logger)
        --(filesystem)--
        +StringPath kivakitCacheFolderPath()
        +StringPath kivakitHomeFolderPath()
        --(messaging)--
        +Listener globalListener()
        +Listener globalListener(Listener)
    }
    
@enduml

