@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core.language.object"
    
    enum ObjectFormatter.Format
    {
        MULTILINE
        SINGLE_LINE
    }
    
    annotation KivaKitFormatProperty
    
    class ObjectFormatter
    {
        --(constructors)--
        +ObjectFormatter(Object)
        +ObjectFormatter(Object, PackagePath)
        --(filtering)--
        +ObjectFormatter filter(PropertyFilter)
    }
    
@enduml

