@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.data.formats.csv.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramCsv
    class DiagramCsv
    {
    }
    
@enduml

