
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.component"
    
    abstract BaseRepeater
    
    interface Component
    
    BaseRepeater <|-- BaseComponent
    Component <|-- BaseComponent
    class BaseComponent
    {
    }
    
    interface JavaTrait
    interface LanguageTrait
    interface PackageTrait
    interface ProjectTrait
    interface RegistryTrait
    interface Repeater
    interface SettingsTrait
    JavaTrait <|-- Component
    ProjectTrait <|-- Component
    PackageTrait <|-- Component
    RegistryTrait <|-- Component
    LanguageTrait <|-- Component
    SettingsTrait <|-- Component
    Repeater <|-- Component
    interface Component
    {
    }
    
    interface Component
    interface Mixin
    interface RepeaterMixin
    Component <|-- ComponentMixin
    Mixin <|-- ComponentMixin
    RepeaterMixin <|-- ComponentMixin
    interface ComponentMixin
    {
        --
        +BaseComponent component()
    }
    
@enduml

