@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core.language.reflection.filters.field"
    
    PropertyFilterSet <|-- AllFields
    class AllFields
    {
        --(constructors)--
        +AllFields(PropertyNamingConvention)
    }
    
    AllFields <|-- NamedField
    class NamedField
    {
        --(constructors)--
        +NamedField(PropertyNamingConvention, String)
    }
    
@enduml

