@startuml

    !include lexakai.theme
    
    title "diagram-count"
    
    abstract BaseCount
    
    interface Countable
    interface Comparable
    interface Contains
    interface ByteSized
    interface Stringable
    
    BaseCount <|-- BitCount
    class BitCount
    {
        --(constructors)--
        #BitCount()
        #BitCount(long)
        --
        +long mask()
        --(collection)--
        +BitCount bitCount(long count)
        +BitCount bitCount(T[] values)
        +BitCount bitsToRepresent(int value)
        +BitCount bitsToRepresent(long value)
        +BitCount perByte()
        +BitCount perCharacter()
        +BitCount perInteger()
        +BitCount perLong()
        +BitCount perShort()
        +BitCount toRepresent(long value)
        +long values()
        --(math)--
        +long maximumSigned()
        +long maximumUnsigned()
        +long minimumSigned()
    }
    
    BaseCount <|-- Bytes
    ByteSized <|-- Bytes
    class Bytes
    {
        --
        +void reverse(byte[] array)
        +void reverse(byte[] array, int fromIndex, int toIndex)
        --(conversion)--
        +double asGigabytes()
        +double asKilobytes()
        +double asMegabytes()
        +double asTerabytes()
        --(primitive)--
        +long asBytes()
        +Bytes bytes(int[] array)
        +Bytes bytes(long[] array)
        +Bytes bytes(byte[] array)
        +Bytes bytes(long bytes)
        +Bytes bytes(Count)
        +Bytes bytes(double bytes)
        +Bytes gigabytes(double gigabytes)
        +Bytes gigabytes(long gigabytes)
        +Bytes kilobytes(long kilobytes)
        +Bytes kilobytes(double kilobytes)
        +Bytes megabytes(double megabytes)
        +Bytes megabytes(long megabytes)
        +Bytes parseBytes(Listener, String value)
        +Bytes primitiveSize(Object)
        +Bytes terabytes(long terabytes)
        +Bytes terabytes(double terabytes)
    }
    
    Countable <|-- ConcurrentMutableCount
    class ConcurrentMutableCount
    {
        --(constructors)--
        +ConcurrentMutableCount()
        +ConcurrentMutableCount(long)
        --
        +long get()
        +void set(long count)
        --(checks)--
        +boolean isGreaterThan(ConcurrentMutableCount that)
        +boolean isLessThan(ConcurrentMutableCount that)
        +boolean isZero()
        --(collection)--
        +void clear()
        --(conversion)--
        +Count asCount()
        +int asInt()
        +long asLong()
        --(math)--
        +long add(BaseCount<?> that)
        +long add(long that)
        +long decrement()
        +long increment()
        +Percent percentOf(Count total)
    }
    
    Level <|-- Confidence
    class Confidence
    {
        --(constructors)--
        #Confidence()
        #Confidence(double)
        --
        +Confidence confidence(double value)
        --(parsing)--
        +Confidence parseConfidence(Listener, String value)
        --(primitive)--
        +int asUnsignedByte()
        +Confidence confidenceForByte(byte level)
        +Confidence confidenceForInt(int value)
    }
    
    BaseCount <|-- Count
    class Count
    {
        --(constructors)--
        #Count()
        #Count(long)
        --(collection)--
        +Count count(Iterable<?>, Maximum)
        +Count count(T[] values)
        +Count count(double value)
        +Count count(Collection<?>)
        +Count count(Iterator<?>, Maximum)
        +Count count(long value)
        +Count count(Iterable<?>)
        +Count count(Iterator<?>)
        +Count count(String text)
        +Count parseCount(Listener, String value)
    }
    
    BaseCount <|-- Estimate
    Stringable <|-- Estimate
    class Estimate
    {
        --(constructors)--
        #Estimate()
        #Estimate(long)
        --
        +Estimate estimate(Collection<?>)
        +Estimate estimate(long value)
        +Estimate estimate(Iterator<?>)
        +Estimate estimate(T[] values)
        +Estimate estimate(Iterable<?>)
        --(parsing)--
        +Estimate parseEstimate(Listener, String value)
    }
    
    class Level
    {
        --(constructors)--
        #Level()
        +Level(double)
        --
        +int compareTo(Level that)
        +Level inverse()
        +Level reciprocal()
        --(checks)--
        +boolean isClose(Level that, double margin)
        +boolean isGreaterThan(Level that)
        +boolean isGreaterThanOrEqualTo(Level that)
        +boolean isLessThan(Level that)
        +boolean isLessThanOrEqualTo(Level that)
        +boolean isZero()
        --(conversion)--
        +byte asByte()
        +Level asLevel()
        +double asZeroToOne()
        --(extension points)--
        #Level onNewInstance(double value)
        --(math)--
        +Percent asPercent()
        +Level divide(Level that)
        +Level minus(Level that)
        +Level plus(Level that)
        +Level times(Level that)
        --(parsing)--
        +Level parseLevel(Listener, String value, boolean lenient)
        --(primitive)--
        +Level levelForByte(byte level)
    }
    
    Contains <|-- LongRange
    class LongRange
    {
        --(constructors)--
        #LongRange()
        +LongRange(long, long)
        --
        +Long constrainTo(Long value)
        --(math)--
        +Long maximum(Long that)
        +Long maximum()
        +Long minimum(Long that)
        +Long minimum()
    }
    
    BaseCount <|-- Maximum
    class Maximum
    {
        --(constructors)--
        #Maximum()
        #Maximum(long)
        --(math)--
        +Maximum maximum(Collection<?>)
        +Maximum maximum(long value)
        +Maximum maximum(Iterator<?>)
        +Maximum maximum(Iterable<?>)
        +Maximum maximum(T[] values)
        +Maximum parseMaximum(Listener, String value)
    }
    
    BaseCount <|-- Minimum
    class Minimum
    {
        --(constructors)--
        #Minimum()
        #Minimum(long)
        --(math)--
        +Minimum minimum(long value)
        +Minimum minimum(Collection<?>)
        +Minimum minimum(Iterable<?>)
        +Minimum minimum(T[] values)
        +Minimum minimum(Iterator<?>)
        +Minimum parseMinimum(Listener, String value)
    }
    
    Countable <|-- MutableCount
    Comparable <|-- MutableCount
    class MutableCount
    {
        --(constructors)--
        +MutableCount()
        +MutableCount(long)
        --
        +long get()
        +void set(long count)
        --(checks)--
        +boolean isGreaterThan(Quantizable that)
        +boolean isLessThan(Quantizable that)
        +boolean isZero()
        --(collection)--
        +void clear()
        --(conversion)--
        +Count asCount()
        +int asInt()
        +long asLong()
        --(math)--
        +long decrement()
        +long increment()
        +long minus(long that)
        +Percent percentOf(Count total)
        +long plus(Quantizable that)
        +long plus(long that)
    }
    
    Comparable <|-- Percent
    class Percent
    {
        --
        +long scale(long value)
        +double scale(double value)
        +int scale(int value)
        --(checks)--
        +boolean isGreaterThan(Percent that)
        +boolean isGreaterThanOrEqualTo(Percent that)
        +boolean isLessThan(Percent that)
        +boolean isLessThanOrEqualTo(Percent that)
        --(collection)--
        +double value()
        --(conversion)--
        +int asInt()
        +Level asLevel()
        +double asUnitValue()
        +double asZeroToOne()
        --(math)--
        +Percent dividedBy(double divisor)
        +Percent inverse()
        +Percent minus(Percent that)
        +Percent of(double percent)
        +Percent parsePercent(Listener, String value)
        +Percent plus(Percent that)
        +Percent times(double scaleFactor)
    }
    
    Countable <|-- Range
    class Range<Value>
    {
        --(constructors)--
        #Range(Value, Value, UpperBound)
        --
        +Range<Count> allCounts()
        +Value constrain(Value)
        +Range<Value> exclusive(Value minimum, Value exclusiveMaximum)
        +void forEach(LoopBody<Value>)
        +Range<Value> inclusive(Value minimum, Value inclusiveMaximum)
        +Value randomValue()
        +UpperBound upperBound()
        --(checks)--
        +boolean isExclusive()
        +boolean isInclusive()
        --(collection)--
        +boolean contains(Value)
        +void forCount(Count, FilteredLoopBody<Value>)
        --(iteration)--
        +void loop(Runnable body)
        --(math)--
        +Value exclusiveMaximum()
        +Value inclusiveMaximum()
        +Value minimum()
    }
    
    Level <|-- Weight
    class Weight
    {
        --(constructors)--
        #Weight()
        --
        +Weight weight(double value)
    }
    
@enduml

