@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.configuration.settings.deployment"
    
    abstract BaseRepeater
    abstract BaseStringConverter
    
    interface Named
    interface Serializable
    
    BaseStringConverter <|-- Deployment.Converter
    class Deployment.Converter
    {
        --(constructors)--
        +Converter(Listener, DeploymentSet)
    }
    
    Settings <|-- Deployment
    Named <|-- Deployment
    Serializable <|-- Deployment
    class Deployment
    {
        --(constructors)--
        +Deployment(String, String)
        --
        +String description()
        --(configuration)--
        +Deployment addDeployment(Deployment)
        +SwitchParser.Builder<Deployment> deploymentSwitchParser(DeploymentSet, String switchName)
    }
    
    BaseRepeater <|-- DeploymentSet
    DeploymentSet "1" o-- "*" Deployment
    class DeploymentSet
    {
        --(constructors)--
        #DeploymentSet()
        --
        +void install(String name)
        --(collection)--
        +boolean isEmpty()
        +int size()
        --(command line parsing)--
        +SwitchParser.Builder<Deployment> switchParser(String name)
        --(configuration)--
        +void add(Deployment)
        +void addAll(Collection<Deployment> deployments)
        +DeploymentSet addDeploymentsIn(Package package_)
        +DeploymentSet addDeploymentsIn(Class<?> relativeTo, String path)
        +DeploymentSet addDeploymentsIn(PackagePath)
        +DeploymentSet addDeploymentsIn(Folder parent)
        +DeploymentSet create()
        +Deployment deployment(String name)
        +Set<Deployment> deployments()
        +DeploymentSet load(Listener, Class<?> relativeTo)
        +DeploymentSet of(Deployment, Deployment... more)
    }
    
@enduml

