@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.configuration.settings"
    
    abstract BaseRepeater
    
    interface Named
    interface Iterable
    
    BaseRepeater <|-- Settings
    Named <|-- Settings
    Iterable <|-- Settings
    Settings --> T : "gets values"
    class Settings
    {
        --
        +boolean has(Class<?> type, Enum<?> instance)
        +boolean has(Class<?> type)
        +boolean has(Class<?> type, InstanceIdentifier)
        +Settings install()
        +Settings of(Object)
        +T settings(Class<T> type, String instance)
        +T settings(Class<T> type, InstanceIdentifier)
        +T settings(Class<T> type, Enum<?> instance)
        +T settings(Class<T> type)
        --(collection)--
        +void clear()
        +Iterator<Object> settings()
        --(lookup)--
        +Settings register(Object settings)
        +Settings register(Object settings, Enum<?> instance)
        +Settings register(Object settings, InstanceIdentifier)
        +Settings registerAll(Settings)
        +Settings registerAll(Collection<Object> settings)
        +Settings registerAllIn(PackagePath)
        +Settings registerAllIn(Package package_)
        +Settings registerAllIn(Class<?> relativeTo, String path)
        +Settings registerAllIn(Folder)
        +Settings registerAllIn(Class<?> type)
        +Settings registerAllWith(Settings)
        +T require(Class<T> type, InstanceIdentifier)
        +T require(Class<T> type, Enum<?> instance)
        +T require(Class<T> type)
    }
    
    Settings <|-- SettingsFolder
    class SettingsFolder
    {
        --(constructors)--
        #SettingsFolder(Folder)
        --(filesystem)--
        +SettingsFolder of(Folder)
    }
    
    Settings <|-- SettingsPackage
    class SettingsPackage
    {
        --(constructors)--
        #SettingsPackage(PackagePath)
        --
        +SettingsPackage of(PackagePath)
        +SettingsPackage of(Package _package)
    }
    
@enduml

