@startuml

    !include lexakai.theme
    
    title "Lookup"
    
    class InstanceIdentifier
    {
        --(constructors)--
        #InstanceIdentifier(String)
        --(identity)--
        +InstanceIdentifier of(Class<?> value)
        +InstanceIdentifier of(String value)
        +InstanceIdentifier of(Enum<?> value)
    }
    
    Registry --> InstanceIdentifier : "locates instances with"
    class Registry
    {
        --
        +Registry of(Object)
        --(lookup)--
        +T lookup(Class<T> type, Enum<?> instance)
        +T lookup(Class<T> type)
        +T lookup(Class<T> type, InstanceIdentifier)
        +T lookup(Class<T> type, String instance)
        +T register(T object, String instance)
        +T register(T object, Enum<?> instance)
        +T register(T object)
        +T register(T object, InstanceIdentifier)
    }
    
@enduml

