@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.reflection.property.filters.field"
    
    PropertyFilterSet <|-- AllFields
    class AllFields
    {
        --(constructors)--
        +AllFields(NamingConvention)
    }
    
    AllFields <|-- NamedField
    class NamedField
    {
        --(constructors)--
        +NamedField(NamingConvention, String)
    }
    
@enduml

