@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.reflection.property.filters.method"
    
    PropertyFilterSet <|-- AllMethods
    class AllMethods
    {
        --(constructors)--
        +AllMethods(NamingConvention)
    }
    
    AllMethods <|-- NamedMethod
    class NamedMethod
    {
        --(constructors)--
        +NamedMethod(NamingConvention, String)
    }
    
@enduml

