@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.language.reflection"
    
    interface Named
    
    Member <|-- Field
    class Field
    {
        --(constructors)--
        +Field(Object, java.lang.reflect.Field)
        --
        +boolean accessible(java.lang.reflect.Field)
        +T annotation(Class<T> annotationClass)
        +Type<?> type()
        --(checks)--
        +boolean isPrimitive()
        --(collection)--
        +ObjectList<Type<T>> genericTypeParameters()
        +Object value()
    }
    
    abstract class Member
    {
        --
        +T annotation(Class<T> annotationClass)
        +Type<?> type()
        --(collection)--
        +List<Type<T>> arrayElementType()
        +List<Type<T>> genericTypeParameters()
        --(naming)--
        +String name()
    }
    
    Member <|-- Method
    class Method
    {
        --(constructors)--
        +Method(Class<?>, String)
        +Method(Class<?>, java.lang.reflect.Method)
        --
        +java.lang.reflect.Method method()
        +Method of(StackTraceElement frame)
        +Type<?> type()
        +Class<?> typeClass()
        --(collection)--
        +List<Type<T>> genericTypeParameters()
        --(naming)--
        +String name()
    }
    
    Named <|-- Type
    class Type<T>
    {
        --
        +A annotation(Class<A> annotationType)
        +A[] annotations(Class<A> annotationType)
        +Constructor<T> constructor(Class<?>... types)
        +boolean declaresToString()
        +Property field(String name)
        +Type<T> forClass(Class<T> type)
        +boolean is(Class<?> type)
        +Method method(String methodName)
        +Type<T> of(Object)
        +Property property(String name)
        +Type<?> superClass()
        +ObjectSet<Type<?>> superInterfaces()
        +Class<T> type()
        --(checks)--
        +boolean hasAnnotation(Class<A> annotationType)
        +boolean isDescendantOf(Class<?> that)
        +boolean isEnum()
        +boolean isInside(PackagePath)
        +boolean isPrimitive()
        +boolean isSystem()
        --(collection)--
        +List<java.lang.reflect.Field> allFields()
        +Type<?> arrayElementType()
        +Set<Enum<?>> enumValues()
        +List<java.lang.reflect.Field> fields(Filter<java.lang.reflect.Field>)
        +List<Type<?>> interfaces()
        +boolean isArray()
        +ObjectList<Property> properties(PropertyFilter)
        +List<Field> reachableFields(Object root, Filter<java.lang.reflect.Field>)
        +List<Object> reachableObjects(Object root, Filter<java.lang.reflect.Field>)
        +List<Object> reachableObjects(Object root)
        +List<Object> reachableObjectsImplementing(Object root, Class<?> _interface)
        +ObjectList<Type<?>> superClasses()
        +ObjectList<Type<?>> superTypes()
        +VariableMap<Object> variables(Object, PropertyFilter)
        +VariableMap<Object> variables(Object, PropertyFilter, Object nullValue)
        --(factory)--
        +T newInstance(Object... parameters)
        +T newInstance()
        --(naming)--
        +Type<T> forName(String className)
        +String fullyQualifiedName()
        +String simpleName()
        +String simpleNameWithoutAnonymousNestedClassNumber()
        --(path)--
        +PackagePath packagePath()
    }
    
@enduml

