@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.interfaces.string"
    
    enum Stringable.Format
    {
        COMPACT
        DEBUG
        FILESYSTEM
        HTML
        LOG
        PROGRAMMATIC
        TEXT
        TO_STRING
        USER_LABEL
        USER_MULTILINE
        USER_SINGLE_LINE
    }
    
    interface StringMapper<Value>
    {
        --(collection)--
        +Value map(String text)
    }
    
    interface StringSource
    {
        --
        +StringSource of(String)
        --(conversion)--
        +String asString()
    }
    
    interface StringSource
    StringSource <|-- Stringable
    Stringable --> Stringable.Format : "formats with"
    interface Stringable
    {
        --(conversion)--
        +String asString(Format)
    }
    
@enduml

