
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.logs.email.internal.lexakai"
    
    interface UmlDiagramIdentifier
    UmlDiagramIdentifier <|-- DiagramLogsEmail
    interface DiagramLogsEmail
    {
    }
    
@enduml

