
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.settings.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramSettings
    class DiagramSettings
    {
    }
    
@enduml

