@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.filesystems.hdfs.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramHdfs
    class DiagramHdfs
    {
    }
    
@enduml

