@startuml

    !include lexakai.theme
    
    title "kivakit-security"
    
    artifact cactus_metadata
    artifact kivakit_conversion
    artifact kivakit_core
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact kivakit_security
    artifact lexakai_annotations
    artifact junit
    artifact hamcrest_core
    artifact annotations
    junit --> hamcrest_core
    kivakit_core --> cactus_metadata
    kivakit_core --> junit
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    kivakit_security --> kivakit_conversion
    kivakit_security --> kivakit_core
    
@enduml
