@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.logs.client.project"
    
    class LogsClientTheme
    {
        --
        +void configure(JFrame, ClientLogPanel, Image icon)
        --(lifecycle)--
        +void initialize()
    }
    
@enduml

