@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.internal.protocols.rest.plugins.jetty.openapi.serialization"
    
    interface JsonSerializer
    
    JsonSerializer <|-- ArraySerializer
    class ArraySerializer<T>
    {
    }
    
    JsonSerializer <|-- ListSerializer
    class ListSerializer
    {
    }
    
    JsonSerializer <|-- MapSerializer
    class MapSerializer
    {
    }
    
    GsonFactory <|-- OpenApiGsonFactory
    class OpenApiGsonFactory
    {
    }
    
    JsonSerializer <|-- SetSerializer
    class SetSerializer
    {
    }
    
    JsonSerializer <|-- StringSerializer
    class StringSerializer
    {
    }
    
@enduml

