
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.protocols.lambda"
    
    abstract BaseComponent
    
    interface Initializable
    interface ComponentMixin
    interface RequestStreamHandler
    interface RegistryTrait
    
    RegistryTrait <|-- LambdaFunction
    class LambdaFunction
    {
        --(constructors)--
        +LambdaFunction(Context)
        +LambdaFunction(String, Version)
    }
    
    RequestStreamHandler <|-- LambdaRequestHandler
    ComponentMixin <|-- LambdaRequestHandler
    class LambdaRequestHandler
    {
    }
    
    BaseComponent <|-- MicroserviceLambdaService
    Initializable <|-- MicroserviceLambdaService
    class MicroserviceLambdaService
    {
        --(constructors)--
        +MicroserviceLambdaService(Microservice<?>)
        --
        +void mount(String lambdaName, Version lambdaVersion, Class<? extends MicroservletRequest> requestType)
        +void mount(String lambdaName, String lambdaVersion, Class<? extends MicroservletRequest> requestType)
    }
    
@enduml

