
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.protocols.rest.openapi"
    
    annotation OpenApiExcludeMember
    
    annotation OpenApiIncludeMember
    
    annotation OpenApiIncludeMemberFromSuperType
    
    annotation OpenApiIncludeType
    
    annotation OpenApiRequestHandler
    
@enduml

