
@startuml

    !include lexakai.theme
    
    title "Microservices"
    
    abstract BaseComponent
    
    interface Startable
    interface Named
    interface Initializable
    interface Stoppable
    
    Application <|-- Microservice
    Startable <|-- Microservice
    Stoppable <|-- Microservice
    Microservice --> MicroserviceMetadata : "has"
    Microservice --> MicroserviceSettings : "has"
    abstract class Microservice<Member>
    {
        --(constructors)--
        +Microservice()
        --
        +MicroserviceCluster<Member> cluster()
        +MicroserviceClusterMember<Member> leader()
        +MicroserviceSettings settings()
        +WebApplication webApplication()
        #void onLeave(MicroserviceClusterMember<Member>)
        #void onMountJettyPlugins(JettyServer)
        --(checks)--
        +boolean isClustered()
        +boolean isLeader()
        --(factory)--
        +GsonFactory gsonFactory()
        +MicroserviceWebApplication onNewWebApplication()
        #MicroserviceClusterMember<Member> onNewMember()
        --(filesystem)--
        #ResourceFolder<?> openApiAssetsFolder()
        #ResourceFolder<?> staticAssetsFolder()
        --(lifecycle)--
        +void onInitialize()
        #void onJoin(MicroserviceClusterMember<Member>)
        --(metadata)--
        +MicroserviceMetadata metadata()
        --(path)--
        +String resolvePath(String mountPath)
        +String rootPath()
        --(service)--
        +MicroserviceGrpcService grpcService()
        +MicroserviceLambdaService lambdaService()
        +MicroserviceGrpcService onNewGrpcService()
        +MicroserviceLambdaService onNewLambdaService()
        +MicroserviceRestService onNewRestService()
        +MicroserviceRestService restService()
    }
    
    class MicroserviceMetadata
    {
        --(constructors)--
        #MicroserviceMetadata(MicroserviceMetadata)
        +MicroserviceMetadata()
        --
        +String description()
        --(functional)--
        +MicroserviceMetadata withDescription(String description)
        +MicroserviceMetadata withName(String name)
        +MicroserviceMetadata withVersion(Version)
        --(identity)--
        +Version version()
        --(naming)--
        +String name()
    }
    
    BaseComponent <|-- MicroserviceRestService
    Initializable <|-- MicroserviceRestService
    MicroserviceRestService --> Microservlet : "mounts"
    MicroserviceRestService o-- Microservice
    abstract class MicroserviceRestService
    {
        --(constructors)--
        +MicroserviceRestService(Microservice<?>)
        --
        +Microservice<?> microservice()
        +void mount(Version, String path, HttpMethod, Class<Request> requestType)
        +void mount(MicroservletRestPath, Microservlet<?,?>)
        +void mount(String path, HttpMethod, Class<Request> requestType)
        +void mountAllOn(MicroservletMountTarget)
        +void onRequestStatistics(MicroservletRequestHandlingStatistics)
        +void onRequested(MicroservletRequest, HttpMethod)
        +void onRequesting(MicroservletRequest, HttpMethod)
        +ObjectSerializer serializer()
        --(command line parsing)--
        +void mountApi(Version, Resource jar, String commandLine, int port)
        +void mountApi(Version, String path, Resource jar, String commandLine, int port)
        --(messaging)--
        +Info openApiInfo()
        --(path)--
        #Version pathToVersion(String path)
        #String rootPath()
        #String versionToPath(Version)
    }
    
    class MicroserviceSettings
    {
        --
        +MicroserviceSettings server(boolean server)
        --(checks)--
        +boolean isServer()
        --(network)--
        +int grpcPort()
        +MicroserviceSettings grpcPort(int grpcPort)
        +int port()
        +MicroserviceSettings port(int port)
    }
    
    BaseComponent <|-- Microservlet
    Named <|-- Microservlet
    Microservlet --> JettyMicroservletRequestCycle : "attaches"
    Microservlet --> MicroservletRequest : "references sub-class"
    Microservlet --> MicroservletResponse : "references sub-class"
    abstract class Microservlet<Request, Response>
    {
        --(constructors)--
        +Microservlet(Class<? extends Request>, Class<? extends Response>)
        --
        +String description()
        +Class<? extends Request> requestType()
        +Response respond(MicroservletRequest)
        +Class<? extends Response> responseType()
        #String get(String key)
        --(collection)--
        #PropertyMap parameters()
        --(conversion)--
        #int asInt(String key)
        #long asLong(String key)
        #T asObject(String key, Class<Converter<String,T>> converterType)
        #T asObject(String key, Converter<String,T>)
        --(extension points)--
        +Response onRespond(Request)
    }
    
@enduml

