@startuml

    !include lexakai.theme
    
    title "Microservlets"
    
    abstract BaseComponent
    abstract BaseMicroservletResponse
    
    interface MicroservletResponse
    interface Named
    interface MicroservletRequestHandler
    interface MicroservletRequest
    
    BaseComponent <|-- BaseMicroservletRequest
    MicroservletRequest <|-- BaseMicroservletRequest
    MicroservletRequestHandler <|-- BaseMicroservletRequest
    abstract class BaseMicroservletRequest
    {
        --(time)--
        #Frequency statisticsReportingFrequency()
    }
    
    BaseComponent <|-- BaseMicroservletResponse
    MicroservletResponse <|-- BaseMicroservletResponse
    abstract class BaseMicroservletResponse
    {
    }
    
    BaseComponent <|-- Microservlet
    Named <|-- Microservlet
    Microservlet --> JettyMicroservletRequestCycle : "attaches"
    Microservlet --> MicroservletRequest : "references sub-class"
    Microservlet --> MicroservletResponse : "references sub-class"
    abstract class Microservlet<Request, Response>
    {
        --(constructors)--
        +Microservlet(Class<? extends Request>, Class<? extends Response>)
        --
        +String description()
        +Response request(MicroservletRequest)
        +Class<? extends Request> requestType()
        +Class<? extends Response> responseType()
        #String get(String key)
        --(collection)--
        #PropertyMap parameters()
        --(conversion)--
        #int asInt(String key)
        #long asLong(String key)
        #T asObject(String key, Class<Converter<String,T>> converterType)
        #T asObject(String key, Converter<String,T>)
        --(extension points)--
        +Response onRequest(Request)
    }
    
    BaseMicroservletResponse <|-- MicroservletErrorResponse
    class MicroservletErrorResponse
    {
        --(collection)--
        +ObjectList<MicroservletError> errors()
        +boolean isEmpty()
        --(messaging)--
        +void send(Listener)
    }
    
    interface Component
    interface MicroservletRequestHandler
    interface ProblemReportingTrait
    interface Validatable
    Validatable <|-- MicroservletRequest
    Component <|-- MicroservletRequest
    ProblemReportingTrait <|-- MicroservletRequest
    MicroservletRequestHandler <|-- MicroservletRequest
    interface MicroservletRequest
    {
        --
        +Class<? extends MicroservletResponse> responseType()
    }
    
    interface MicroservletRequestHandler
    {
        --
        +void onRequestStatistics(MicroservletRequestStatistics)
        +MicroservletResponse request(String path)
        --(extension points)--
        +MicroservletResponse onRequest()
    }
    
    interface Component
    interface ProblemReportingTrait
    interface Validatable
    Validatable <|-- MicroservletResponse
    Component <|-- MicroservletResponse
    ProblemReportingTrait <|-- MicroservletResponse
    interface MicroservletResponse
    {
    }
    
@enduml

