
@startuml

    !include lexakai.theme
    
    title "kivakit-commandline"
    
    artifact cactus_build_metadata
    artifact kivakit_collections
    artifact kivakit_commandline
    artifact kivakit_conversion
    artifact kivakit_core
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact kivakit_validation
    artifact lexakai_annotations
    artifact annotations
    kivakit_commandline --> kivakit_collections
    kivakit_commandline --> kivakit_conversion
    kivakit_commandline --> kivakit_core
    kivakit_commandline --> kivakit_validation
    kivakit_core --> cactus_build_metadata
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    
@enduml
