@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.network.socket"
    
    Project <|-- SocketProject
    class SocketProject
    {
        --(constructors)--
        #SocketProject()
        --
        +SocketProject get()
    }
    
@enduml

