@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.component.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramComponent
    class DiagramComponent
    {
    }
    
@enduml

