
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.primitive.collections.internal.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveArray
    class DiagramPrimitiveArray
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveArrayArray
    class DiagramPrimitiveArrayArray
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveArrayBitIo
    class DiagramPrimitiveArrayBitIo
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveCollection
    class DiagramPrimitiveCollection
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveList
    class DiagramPrimitiveList
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveMap
    class DiagramPrimitiveMap
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveMultiMap
    class DiagramPrimitiveMultiMap
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveSet
    class DiagramPrimitiveSet
    {
    }
    
    UmlDiagramIdentifier <|-- DiagramPrimitiveSplitArray
    class DiagramPrimitiveSplitArray
    {
    }
    
@enduml

