
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.logs.file.internal.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramLogsFile
    class DiagramLogsFile
    {
    }
    
@enduml

