
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.resource"
    
    abstract BaseStringConverter
    abstract BaseResourceList
    
    interface Named
    interface Comparable
    interface UriIdentified
    interface Matcher
    interface ResourcePathed
    interface Matchable
    
    ObjectList <|-- BaseResourceList
    abstract class BaseResourceList<T>
    {
        --
        +byte[] digest()
        --(collection)--
        +BaseResourceList<T> matching(Extension)
        +BaseResourceList<T> relativeTo(ResourceFolder<?>)
        +BaseResourceList<T> sortedLargestToSmallest()
        +BaseResourceList<T> sortedOldestToNewest()
        +Bytes totalSize()
        #BaseResourceList<T> newResourceList()
        --(factory)--
        #T newResource(ResourcePath)
        --(filtering)--
        #boolean accepts(FileName)
        --(math)--
        +Resource largest()
        +Resource smallest()
    }
    
    enum Resource.Can
    {
        DELETE
        RENAME
    }
    
    BaseStringConverter <|-- Resource.Converter
    class Resource.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    BaseStringConverter <|-- ResourcePath.Converter
    class ResourcePath.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    BaseStringConverter <|-- ResourceFolder.Converter
    class ResourceFolder.Converter
    {
        --(constructors)--
        +Converter(Listener)
    }
    
    enum CopyMode
    {
        DO_NOT_OVERWRITE
        OVERWRITE
        UPDATE
    }
    
    interface Deletable
    {
        --(filesystem)--
        +boolean delete()
    }
    
    Named <|-- Extension
    Matchable <|-- Extension
    class Extension
    {
        --(constructors)--
        #Extension(String)
        --
        +Codec codec()
        +boolean ends(ResourcePath)
        +boolean ends(Resource)
        --(checks)--
        +boolean endsWith(Extension)
        +boolean isArchive()
        +boolean isExecutable()
        --(collection)--
        +Count length()
        --(filesystem)--
        +List<Extension> archive()
        +List<Extension> executable()
        +Extension gzipped()
        +List<Extension> known()
        +Extension parseExtension(Listener, String value)
        +Extension parseExtension(String value)
        +Extension withExtension(Extension)
    }
    
    Named <|-- FileName
    Comparable <|-- FileName
    class FileName
    {
        --(constructors)--
        #FileName(String)
        --
        +boolean matches(Pattern)
        --(checks)--
        +boolean endsWith(String suffix)
        +boolean endsWith(Extension)
        +boolean startsWith(String prefix)
        --(filesystem)--
        +FilePath asPath()
        +FileName base()
        +Extension compoundExtension()
        +FileName date(LocalTime)
        +FileName date(LocalTime, ZoneId)
        +FileName date()
        +FileName dateTime(LocalTime)
        +FileName dateTime(LocalTime, ZoneId)
        +FileName dateTime()
        +Extension extension()
        +Matcher<FileName> fileNameMatcher()
        +FileName normalized()
        +FileName parseFileName(Listener, String name)
        +FileName prefixedWith(String prefix)
        +FileName time(LocalTime, ZoneId)
        +FileName time(LocalTime)
        +FileName toLowerCase()
        +FileName toUpperCase()
        +FileName withExtension(Extension)
        +FileName withSuffix(String suffix)
        +FileName withoutCompoundExtension()
        +FileName withoutExtension(Extension)
        +FileName withoutExtension()
        +FileName withoutKnownExtensions()
        --(matching)--
        +Matcher<Resource> matcher()
        --(time)--
        +LocalTime localDateTime()
        +LocalTime localDateTime(Listener)
        +LocalTime parseDateTime(Listener, String dateTime)
        +LocalTime parseDateTime(Listener, String dateTime, ZoneId)
    }
    
    interface Renamable
    {
        --(filesystem)--
        +boolean renameTo(ResourcePathed)
    }
    
    interface ByteSized
    interface CreatedAt
    interface Deletable
    interface Modifiable
    interface ModifiedAt
    interface ReadableResource
    interface Repeater
    interface ResourcePathed
    interface Resourceful
    interface StringSource
    interface UriIdentified
    ResourcePathed <|-- Resource
    Modifiable <|-- Resource
    ModifiedAt <|-- Resource
    CreatedAt <|-- Resource
    Deletable <|-- Resource
    ByteSized <|-- Resource
    StringSource <|-- Resource
    ReadableResource <|-- Resource
    Repeater <|-- Resource
    Resourceful <|-- Resource
    UriIdentified <|-- Resource
    Resource --> Codec : "uses"
    interface Resource
    {
        --
        +ObjectSet<Can> can()
        +boolean can(Can ability)
        +Codec codec()
        +void dematerialize()
        +Resource relativeTo(ResourceFolder<?>)
        +Resource resolve(Listener, ResourcePath)
        +Resource resolve(Listener, String identifier)
        +Resource resolve(Listener, ResourceIdentifier)
        --(checks)--
        +boolean endsWith(String end)
        +boolean hasParent()
        +boolean isEmpty()
        +boolean isLocal()
        +boolean isMaterializable()
        +boolean isOlderThan(Resource that)
        +boolean isPackaged()
        +boolean isRemote()
        +boolean isSame(Resource that)
        --(command line parsing)--
        +ArgumentParser.Builder<Resource> argumentParser(Listener, String description)
        +SwitchParser.Builder<Resource> resourceSwitchParser(Listener, String name, String description)
        --(conversion)--
        +WritableResource asWritable()
        --(filesystem)--
        +void ensureExists()
        +boolean exists()
        +ResourceFolder<?> parent()
        +boolean renameTo(Resource that)
        +void safeCopyTo(ResourceFolder<?> destination, CopyMode)
        +void safeCopyTo(WritableResource destination, CopyMode)
        +void safeCopyTo(WritableResource destination, CopyMode, ProgressReporter)
        +void safeCopyTo(ResourceFolder<?> destination, CopyMode, ProgressReporter)
        --(functional)--
        +Resource materialized(ProgressReporter)
        --(identity)--
        +ResourceIdentifier identifier(String identifier)
    }
    
    interface Matchable
    interface Repeater
    interface ResourcePathed
    interface UriIdentified
    Repeater <|-- ResourceFolder
    UriIdentified <|-- ResourceFolder
    ResourcePathed <|-- ResourceFolder
    Matchable <|-- ResourceFolder
    interface ResourceFolder<T>
    {
        --
        +Resource resource(ResourcePathed name)
        +Resource resource(FileName)
        +Resource resource(String name)
        --(checks)--
        +boolean hasTrailingSlash()
        +boolean isMaterialized()
        +boolean isWritable()
        --(collection)--
        +boolean contains(ResourcePathed that)
        +boolean isEmpty()
        +ResourceList nestedResources(Matcher<ResourcePathed>)
        +ResourceList nestedResources()
        +ResourceList resources()
        +ResourceList resources(Matcher<ResourcePathed>)
        --(filesystem)--
        +ResourceFolder<?> absolute()
        +void copyTo(Folder destination, CopyMode, Matcher<ResourcePathed>, ProgressReporter)
        +void copyTo(Folder destination, CopyMode, ProgressReporter)
        +boolean delete()
        +boolean exists()
        +T folder(String path)
        +List<T> folders()
        +ResourceFolderIdentifier identifier()
        +ResourceFolderIdentifier identifier(String identifier)
        +Folder materialize()
        +Folder materializeTo(Folder)
        +ResourceFolder<?> mkdirs()
        +List<T> nestedFolders(Matcher<T>)
        +ResourceFolder<?> newFolder(ResourcePath relativePath)
        +ResourceFolder<?> parent()
        +ResourceFolder<?> relativeTo(ResourceFolder<?>)
        +boolean renameTo(ResourceFolder<?>)
        +ResourceFolder<?> resolve(Listener, ResourceFolderIdentifier)
        +ResourceFolder<?> resolve(Listener, String identifier)
        +void safeCopyTo(ResourceFolder<?>, CopyMode, Matcher<ResourcePathed>, ProgressReporter)
        +void safeCopyTo(ResourceFolder<?>, CopyMode, ProgressReporter)
        +WritableResource temporaryFile(FileName baseName)
        +WritableResource temporaryFile(FileName baseName, Extension)
        +ResourceFolder<?> temporaryFolder(FileName baseName)
        +ResourceFolder<?> withTrailingSlash()
        --(matching)--
        +Matcher<ResourcePathed> matchAllIn()
        +Matcher<ResourcePathed> matchAllUnder()
    }
    
    class ResourceFolderIdentifier
    {
        --(constructors)--
        +ResourceFolderIdentifier(String)
        --(filesystem)--
        +ResourceFolder<?> resolve(Listener)
        --(identity)--
        +String identifier()
    }
    
    Matcher <|-- ResourceGlob
    class ResourceGlob
    {
        --(constructors)--
        #ResourceGlob(Matcher<ResourcePathed>)
        --
        +ResourceGlob in(ResourceFolder<?>)
        +ResourceGlob select(Matchable<ResourcePathed> that)
        +ResourceGlob under(ResourceFolder<?>)
        --(logical)--
        +ResourceGlob not()
        --(matching)--
        +ResourceGlob match(Matcher<ResourcePathed>)
        +ResourceGlob match(Pattern)
        +ResourceGlob match(String glob)
        +ResourceGlob match(Matchable<ResourcePathed>)
        +ResourceGlob matchAll()
        +ResourceGlob matchAllIn(ResourceFolder<?>)
        +ResourceGlob matchAllUnder(ResourceFolder<?>)
        --(math)--
        +ResourceGlob minus(Matchable<ResourcePathed> that)
        +ResourceGlob plus(Matchable<ResourcePathed> that)
    }
    
    class ResourceIdentifier
    {
        --(constructors)--
        +ResourceIdentifier(String)
        --
        +Resource resolve(Listener)
        --(identity)--
        +String identifier()
    }
    
    BaseResourceList <|-- ResourceList
    ResourceList --> Resource : "contains"
    class ResourceList
    {
        --(constructors)--
        +ResourceList()
        +ResourceList(Iterable<? extends Resource>)
        --(collection)--
        +ResourceList resourceList(Resource... resources)
        +ResourceList resourceList(Iterable<? extends Resource> resources)
    }
    
    StringPath <|-- ResourcePath
    UriIdentified <|-- ResourcePath
    ResourcePathed <|-- ResourcePath
    class ResourcePath
    {
        --(constructors)--
        #ResourcePath(ResourcePath)
        #ResourcePath(StringList, List<String>)
        #ResourcePath(StringList, String, List<String>)
        --(checks)--
        +boolean hasScheme()
        +boolean hasTrailingSlash()
        --(collection)--
        +StringList schemes()
        --(filesystem)--
        +File asFile()
        +Extension extension()
        +FileName fileName()
        --(path)--
        +ResourcePath absolute()
        +FilePath asFilePath()
        +ResourcePath normalized()
        +ResourcePath parseResourcePath(Listener, String path)
        +ResourcePath parseUnixResourcePath(Listener, String path)
        +ResourcePath relativeTo(ResourcePath)
        +ResourcePath resourcePath(StringPath)
        +SwitchParser.Builder<ResourcePath> resourcePathSwitchParser(Listener, String name, String description)
        +FilePath withExtension(Extension)
        +ResourcePath withSchemes(StringList schemes)
        +ResourcePath withoutSchemes()
    }
    
    interface UriIdentified
    UriIdentified <|-- ResourcePathed
    ResourcePathed --> ResourcePath : "supplies"
    interface ResourcePathed
    {
        --
        +boolean matches(Matcher<String>)
        --(filesystem)--
        +java.io.File asJavaFile()
        +FileName baseName()
        +Extension compoundExtension()
        +Extension extension()
        +FileName fileName()
        +boolean hasExtension(Extension)
        --(network)--
        +URL url()
        --(path)--
        +ResourcePath path()
    }
    
    interface Resourceful
    {
        --
        +Resource resource()
    }
    
    interface UriIdentified
    {
        --(network)--
        +URI uri()
    }
    
@enduml

