@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.resource.project"
    
    KryoTypes <|-- ResourceKryoTypes
    class ResourceKryoTypes
    {
        --(constructors)--
        +ResourceKryoTypes()
    }
    
@enduml

