@startuml

    !include lexakai.theme
    
    title "diagram-primitive"
    
    class Arrays
    {
        --
        +T[] concatenate(T[] a, T[] b)
        +long[] reverse(long[] elements)
        +int[] reverse(int[] elements)
        +void reverseRange(long[] array, int fromIndex, int toIndex)
        --(collection)--
        +boolean contains(T[] array, T object)
        --(conversion)--
        +String asHexadecimalString(byte[] bytes)
    }
    
    class Booleans
    {
        --(checks)--
        +boolean isFalse(String)
        +boolean isTrue(String)
    }
    
    class Doubles
    {
        --
        +String format(double value, int decimals)
        +String format(double value)
        +double inRange(double value, double minimum, double maximum)
        +int rounded(double value)
        --(checks)--
        +boolean isBetweenInclusive(double value, double minimum, double maximum)
        --(parsing)--
        +double fastParse(String value, double denominator)
    }
    
    class Ints
    {
        --
        +String commaSeparated(int value)
        +int digits(int value)
        +int forHighLow(int highWord, int lowWord)
        +int high(int value)
        +int inRange(int value, int minimum, int maximum)
        +int low(int value)
        +int powerOfTen(int power)
        +int quantized(int value, int quantum)
        +int rounded(double value)
        +int signExtend(int value, int bits)
        --(checks)--
        +boolean isBetweenExclusive(int value, int low, int high)
        +boolean isBetweenInclusive(int value, int low, int high)
        --(conversion)--
        +String toHex(int value, int length)
        +String toHex(int value)
        --(parsing)--
        +int parseFast(String text, int invalidValue)
        +int parseFast(String text)
        +int parseFastNaturalNumber(String)
        +int parseInt(Listener, String text)
    }
    
    class Longs
    {
        --
        +String commaSeparated(long value)
        +long forHighLow(int high, int low)
        +int high(long value)
        +long inRange(long value, long min, long max)
        +int low(long value)
        --(checks)--
        +boolean isBetweenExclusive(long value, long low, long high)
        +boolean isBetweenInclusive(long value, long low, long high)
        --(conversion)--
        +String toHex(long value, long length)
        +String toHex(long value)
        --(parsing)--
        +long parseFast(String)
        +long parseFast(String, long invalid)
        +long parseFastNaturalNumber(String)
        --(search)--
        +boolean searchWords(long value, int bits, int searchFor)
    }
    
    class Primes
    {
        --
        +void main(String[] args)
        +int primePowerOfTwo(int value)
        --(checks)--
        +boolean isPrime(long)
        --(collection)--
        +long primeAllocationSize(long size)
    }
    
@enduml

