
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.network.http.secure"
    
    HttpGetResource <|-- SecureHttpGetResource
    class SecureHttpGetResource
    {
        --(constructors)--
        +SecureHttpGetResource(SecureHttpNetworkLocation, NetworkAccessConstraints)
        +SecureHttpGetResource(SecureHttpNetworkLocation)
    }
    
    HttpNetworkLocation <|-- SecureHttpNetworkLocation
    SecureHttpNetworkLocation --> SecureHttpGetResource : "creates"
    SecureHttpNetworkLocation --> SecureHttpPostResource : "creates"
    class SecureHttpNetworkLocation
    {
        --(constructors)--
        +SecureHttpNetworkLocation(NetworkPath)
    }
    
    HttpPostResource <|-- SecureHttpPostResource
    class SecureHttpPostResource
    {
        --(constructors)--
        +SecureHttpPostResource(NetworkLocation, NetworkAccessConstraints)
        +SecureHttpPostResource(SecureHttpNetworkLocation)
    }
    
@enduml

