
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core.language.packaging"
    
    StringPath <|-- PackageReference
    class PackageReference
    {
        --
        +Set<PackageReference> filesystemSubPackages(Listener)
        +Set<PackageReference> jarSubPackages(Listener)
        +PackageReference packageReference(Class<?> type, StringPath)
        +PackageReference packageReference(StringPath)
        +PackageReference packageReference(Class<?> type)
        +Class<?> packageType()
        --(checks)--
        +boolean hasPackageType()
        +boolean isPackageReference(String path)
        --(collection)--
        +boolean contains(PackageReference that)
        +boolean containsNested(PackageReference that)
        --(conversion)--
        +String asSlashSeparated()
        --(functional)--
        +PackageReference withPackageType(Class<?> type)
        --(parsing)--
        +PackageReference parsePackageReference(Listener, Class<?> type, String relativePath)
        +PackageReference parsePackageReference(Listener, String path)
    }
    
@enduml

