
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.protocols.rest.health"
    
    abstract BaseMicroservletResponse
    abstract BaseMicroservletRequest
    
    BaseMicroservletRequest <|-- HealthLiveRequest
    class HealthLiveRequest
    {
    }
    
    BaseMicroservletResponse <|-- HealthLiveRequest.HealthLiveResponse
    class HealthLiveRequest.HealthLiveResponse
    {
    }
    
    BaseMicroservletRequest <|-- HealthReadyRequest
    class HealthReadyRequest
    {
    }
    
    BaseMicroservletResponse <|-- HealthReadyRequest.HealthReadyResponse
    class HealthReadyRequest.HealthReadyResponse
    {
    }
    
@enduml

