@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.resource.project"
    
    KryoTypes <|-- CoreResourceKryoTypes
    class CoreResourceKryoTypes
    {
        --(constructors)--
        +CoreResourceKryoTypes()
    }
    
    Project <|-- ResourceProject
    class ResourceProject
    {
        --(constructors)--
        #ResourceProject()
        --
        +ResourceProject get()
    }
    
@enduml

