@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.filesystems.hdfs.proxy.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramHdfsProxy
    class DiagramHdfsProxy
    {
    }
    
@enduml

