
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.ui.desktop.event"
    
    class EventCoalescer
    {
        --(constructors)--
        +EventCoalescer(Frequency, Runnable)
        --(lifecycle)--
        +void startTimer()
    }
    
@enduml

