
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.ui.desktop.theme.vanhelsing"
    
    KivaKitTheme <|-- KivaKitVanHelsingTheme
    class KivaKitVanHelsingTheme
    {
        --(constructors)--
        +KivaKitVanHelsingTheme()
    }
    
@enduml

