
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.internal.protocols.rest.plugins.jetty.filter"
    
    abstract BaseComponent
    abstract BaseMounted
    
    interface Filter
    interface ComponentMixin
    interface TryTrait
    interface RestProblemReportingTrait
    
    BaseComponent <|-- BaseMounted
    RestProblemReportingTrait <|-- BaseMounted
    abstract class BaseMounted
    {
        --(constructors)--
        #BaseMounted(RestService)
        --
        #void measure(RestPath, Runnable code)
    }
    
    BaseComponent <|-- JettyMicroservletFilter
    Filter <|-- JettyMicroservletFilter
    TryTrait <|-- JettyMicroservletFilter
    RestProblemReportingTrait <|-- JettyMicroservletFilter
    JettyMicroservletFilter --> JettyRestRequestCycle : "creates"
    JettyMicroservletFilter "1" o-- "many" Microservlet : "mounts on paths"
    JettyMicroservletFilter o-- RestService
    class JettyMicroservletFilter
    {
        --(constructors)--
        +JettyMicroservletFilter(RestService)
        --
        +MountedMicroservlet microservlet(RestPath)
        +void mount(RestPath, Microservlet<?,?>)
        +void mount(MountedApi)
        +Collection<MountedApi> mountedApis()
        --(filtering)--
        +^void doFilter(ServletRequest, ServletResponse, FilterChain)
        --(path)--
        +Set<RestPath> microservletPaths()
    }
    
    FilterHolder <|-- JettyMicroservletFilterHolder
    ComponentMixin <|-- JettyMicroservletFilterHolder
    JettyMicroservletFilterHolder o-- JettyMicroservletFilter
    class JettyMicroservletFilterHolder
    {
        --(constructors)--
        +JettyMicroservletFilterHolder(RestService)
        --(filtering)--
        +JettyMicroservletFilter filter()
    }
    
    BaseMounted <|-- MountedApi
    TryTrait <|-- MountedApi
    class MountedApi
    {
        --(constructors)--
        +MountedApi(RestService)
        --
        +MountedApi jar(Resource jar)
        +boolean maybeLaunch()
        --(checks)--
        +boolean isAlive()
        +boolean isReady()
        --(command line parsing)--
        +MountedApi commandLine(StringList commandLine)
        --(identity)--
        +MountedApi version(Version)
        --(messaging)--
        +boolean handleRequest(HttpMethod, JettyRestRequestCycle)
        --(network)--
        +MountedApi port(int port)
        +Port port()
        +URI uri(String path)
        +URI uri()
        --(path)--
        +MountedApi path(RestPath)
        +RestPath path()
    }
    
    BaseMounted <|-- MountedMicroservlet
    class MountedMicroservlet
    {
        --(constructors)--
        +MountedMicroservlet(RestService)
        --
        +Microservlet<?,?> microservlet()
        --(messaging)--
        +void handleRequest(HttpMethod, RestRequestCycle)
        --(path)--
        +RestPath path()
    }
    
@enduml

