
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.settings.stores.zookeeper"
    
    abstract BaseComponent
    abstract BaseSettingsStore
    
    interface Watcher
    interface ZookeeperChangeListener
    interface ZookeeperConnectionListener
    
    interface ZookeeperConnection.ListenerMethod
    {
        --
        +void on(StringPath)
    }
    
    class ZookeeperConnection.Settings
    {
    }
    
    enum ZookeeperConnection.State
    {
        CONNECTED
        DISCONNECTED
    }
    
    interface ZookeeperChangeListener
    {
        --
        +void onNodeChildrenChanged(StringPath)
        +void onNodeCreated(StringPath)
        +void onNodeDataChanged(StringPath)
        +void onNodeDeleted(StringPath)
    }
    
    BaseComponent <|-- ZookeeperConnection
    Watcher <|-- ZookeeperConnection
    class ZookeeperConnection
    {
        --(constructors)--
        +ZookeeperConnection(ZookeeperConnectionListener, ZookeeperChangeListener)
        --
        +CreateMode defaultCreateMode()
        +void onConnection(Runnable code)
        +void watch(StringPath)
        +void watchRoot()
        +ZooKeeper zookeeper()
        --(checks)--
        +boolean isConnected()
        --(collection)--
        +StringList children(StringPath)
        --(filesystem)--
        +boolean delete(StringPath)
        +boolean exists(StringPath)
        --(path)--
        +StringPath create(StringPath, byte[] data, List<ACL>, CreateMode)
        +StringPath root()
        +Map<StringPath,Watcher> watchers()
        --(read)--
        +byte[] read(StringPath)
        --(write)--
        +boolean write(StringPath, byte[] data)
    }
    
    interface ZookeeperConnectionListener
    {
        --
        +void onConnected()
        +void onDisconnected()
    }
    
    BaseSettingsStore <|-- ZookeeperSettingsStore
    ZookeeperChangeListener <|-- ZookeeperSettingsStore
    ZookeeperConnectionListener <|-- ZookeeperSettingsStore
    class ZookeeperSettingsStore
    {
        --(constructors)--
        +ZookeeperSettingsStore(CreateMode, ObjectSerializer)
        +ZookeeperSettingsStore(ObjectSerializer)
        --
        #byte[] onSerialize(Object)
        #void onSettingsDeleted(StringPath, SettingsObject)
        #void onSettingsUpdated(StringPath, SettingsObject)
        --(extension points)--
        #T onDeserialize(byte[] data, Class<T> type)
        --(path)--
        +StringPath root()
        +StringPath unflatten(StringPath)
        --(read)--
        +SettingsObject loadSettings(StringPath)
    }
    
@enduml

