@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.kernel.interfaces.string"
    
    interface StringSource
    {
        --
        +StringSource of(String)
        +String string()
    }
    
@enduml

