
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core.os"
    
    interface Named
    interface Listener
    interface Flushable
    
    Flushable <|-- Console
    class Console
    {
        --
        +Console get()
        +void print(OutputType, String text, Object... arguments)
        +void print(String text, Object... arguments)
        +void println(OutputType, String text, Object... arguments)
        +void println(String text, Object... arguments)
        --(write)--
        +PrintWriter printWriter()
    }
    
    Listener <|-- ConsoleWriter
    class ConsoleWriter
    {
    }
    
    Named <|-- OperatingSystem
    class OperatingSystem
    {
        --
        +String exec(File folder, String... command)
        +OperatingSystem get()
        +String java()
        +String javaHome()
        +String processor()
        +String property(String variable)
        --(checks)--
        +boolean isMac()
        +boolean isUnix()
        +boolean isWindows()
        --(collection)--
        +VariableMap<String> environmentVariables()
        --(identity)--
        +int processIdentifier()
    }
    
    enum Console.OutputType
    {
        ERROR
        NORMAL
    }
    
    class Processes
    {
        --
        +void redirectStandardOutToConsole(Process)
        --(status)--
        +void redirectStandardErrorToConsole(Process)
        --(thread)--
        +void waitFor(Process)
        --(write)--
        +String captureOutput(Process)
    }
    
@enduml

