
@startuml

    !include lexakai.theme
    
    title "diagram-progress"
    
    interface ProgressReporter
    
    Multicaster <|-- BroadcastingProgressReporter
    ProgressReporter <|-- BroadcastingProgressReporter
    class BroadcastingProgressReporter
    {
        --(constructors)--
        #BroadcastingProgressReporter()
        #BroadcastingProgressReporter(BroadcastingProgressReporter)
        --
        +long at()
        +BroadcastingProgressReporter create(Listener, String itemName)
        +BroadcastingProgressReporter create(Listener)
        +BroadcastingProgressReporter create(Listener, String itemName, BaseCount<?> steps)
        +BroadcastingProgressReporter create()
        +BroadcastingProgressReporter createConcurrent(Listener, String itemName, BaseCount<?> steps)
        +BroadcastingProgressReporter createConcurrent(Listener)
        +BroadcastingProgressReporter createConcurrent(Listener, String itemName)
        +void feedback(String message)
        #void at(long at)
        #long increase(long increase)
        --(factory)--
        #BroadcastingProgressReporter newInstance()
        --(functional)--
        +BroadcastingProgressReporter withItemName(String itemName)
        +BroadcastingProgressReporter withPhase(String phase)
        +BroadcastingProgressReporter withSteps(BaseCount<?> steps)
        --(iteration)--
        +void next(long increase)
        --(math)--
        #long increment()
    }
    
    BroadcastingProgressReporter <|-- ConcurrentBroadcastingProgressReporter
    class ConcurrentBroadcastingProgressReporter
    {
        --(constructors)--
        #ConcurrentBroadcastingProgressReporter()
        +ConcurrentBroadcastingProgressReporter(BroadcastingProgressReporter)
    }
    
    interface ProgressListener
    {
        --
        +void at(Percent at)
    }
    
    interface Resettable
    Resettable <|-- ProgressReporter
    ProgressReporter --> ProgressListener : "reports progress to"
    interface ProgressReporter
    {
        --
        +ProgressReporter phase(String phase)
        +ProgressReporter steps(BaseCount<?> steps)
        --(checks)--
        +boolean isIndefinite()
        --(collection)--
        +Count steps()
        --(iteration)--
        +void next()
        +void next(Count steps)
        +void next(int steps)
        --(lifecycle)--
        +void end()
        +void end(String message, Object... arguments)
        +ProgressReporter start()
        +ProgressReporter start(String label)
        --(logical)--
        +ProgressReporter none()
        --(messaging)--
        +ProgressReporter listener(ProgressListener)
        --(read)--
        +ProgressiveInputStream progressiveInput(InputStream)
        --(write)--
        +ProgressiveOutputStream progressiveOutput(OutputStream)
    }
    
    InputStream <|-- ProgressiveInputStream
    class ProgressiveInputStream
    {
        --(constructors)--
        +ProgressiveInputStream(InputStream)
        +ProgressiveInputStream(InputStream, ProgressReporter)
    }
    
    OutputStream <|-- ProgressiveOutputStream
    class ProgressiveOutputStream
    {
        --(constructors)--
        +ProgressiveOutputStream(OutputStream)
        +ProgressiveOutputStream(OutputStream, ProgressReporter)
    }
    
@enduml

