
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.annotations.code.quality"
    
    enum Audience
    {
        AUDIENCE_INTERNAL
        AUDIENCE_PUBLIC
        AUDIENCE_SERVICE_PROVIDER
        AUDIENCE_SERVICE_PROVIDER_INTERFACE
    }
    
    enum Documentation
    {
        DOCUMENTATION_INSUFFICIENT
        DOCUMENTATION_NOT_NEEDED
        DOCUMENTATION_UNDETERMINED
        DOCUMENTED
        UNDOCUMENTED
    }
    
    annotation MethodQuality
    
    enum Stability
    {
        STABILITY_UNDETERMINED
        STABLE
        STABLE_EXTENSIBLE
        UNSTABLE
    }
    
    enum Testing
    {
        TESTED
        TESTING_INSUFFICIENT
        TESTING_NOT_NEEDED
        TESTING_UNDETERMINED
        UNTESTED
    }
    
    annotation TypeQuality
    
@enduml

