
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.core"
    
    Project <|-- KivaKit
    class KivaKit
    {
        --(filesystem)--
        +Path cacheFolderPath()
        +Path homeFolderPath()
    }
    
@enduml

