
@startuml

    !include lexakai.theme
    
    title "kivakit-core"
    
    artifact cactus_metadata
    artifact kivakit_core
    artifact kivakit_interfaces
    artifact kivakit_mixins
    artifact lexakai_annotations
    artifact annotations
    kivakit_core --> cactus_metadata
    kivakit_core --> kivakit_interfaces
    kivakit_core --> kivakit_mixins
    kivakit_interfaces --> annotations
    kivakit_interfaces --> lexakai_annotations
    
@enduml
