
@startuml

    !include lexakai.theme
    
    title "Projects"
    
    abstract BaseRepeater
    
    interface Initializable
    interface ProjectTrait
    interface JavaTrait
    interface NamedObject
    interface LanguageTrait
    interface RegistryTrait
    
    Project <|-- KivaKit
    class KivaKit
    {
        --(filesystem)--
        +Path cacheFolderPath()
        +Path homeFolderPath()
    }
    
    BaseRepeater <|-- Project
    Initializable <|-- Project
    JavaTrait <|-- Project
    ProjectTrait <|-- Project
    RegistryTrait <|-- Project
    LanguageTrait <|-- Project
    NamedObject <|-- Project
    Project "1" --> "*" Class : "depends on"
    abstract class Project
    {
        --
        +ObjectSet<Class<? extends Project>> dependencies()
        +void onInitialized()
        +void onInitializing()
        +String property(String key)
        +T resolveProject(Class<T> type)
        +void visitDependencies(Visitor)
        --(building)--
        +Build build()
        --(collection)--
        +VariableMap<String> properties()
        --(identity)--
        +String artifactId()
        +String groupId()
        +Version kivakitVersion()
        +Version projectVersion()
    }
    
@enduml

