@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.service.registry.project"
    
    KryoTypes <|-- ServiceRegistryKryoTypes
    class ServiceRegistryKryoTypes
    {
        --(constructors)--
        +ServiceRegistryKryoTypes()
    }
    
@enduml

