
@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.microservice.protocols.grpc"
    
    abstract BaseComponent
    
    interface Startable
    interface Initializable
    interface Stoppable
    interface MicroservletMountTarget
    interface TryTrait
    
    BaseComponent <|-- MicroserviceGrpcClient
    class MicroserviceGrpcClient
    {
        --(constructors)--
        +MicroserviceGrpcClient(Port, Version)
        --
        +T request(String path, MicroservletRequest, Class<T> responseType)
        +MicroservletFutureResponse<T> requestFuture(String path, MicroservletRequest, Class<T> responseType)
        --(lifecycle)--
        +void stop()
        --(lookup)--
        #void onRegisterObjectSerializers()
    }
    
    BaseComponent <|-- MicroserviceGrpcService
    Initializable <|-- MicroserviceGrpcService
    Startable <|-- MicroserviceGrpcService
    Stoppable <|-- MicroserviceGrpcService
    TryTrait <|-- MicroserviceGrpcService
    MicroservletMountTarget <|-- MicroserviceGrpcService
    MicroserviceGrpcService --> Microservlet : "mounts"
    class MicroserviceGrpcService
    {
        --(constructors)--
        +MicroserviceGrpcService(Microservice<?>)
        --
        +^void mount(String path, Class<? extends MicroservletRequestHandler> requestHandlerType)
        --(filesystem)--
        +void writeProtoFilesTo(Folder)
    }
    
    BaseComponent <|-- MicroservletFutureResponse
    class MicroservletFutureResponse<T>
    {
        --(constructors)--
        +MicroservletFutureResponse(MicroservletResponderFutureStub, MicroservletGrpcRequestProtobuf, Class<T>)
        --
        +T get()
    }
    
@enduml

