@startuml

    !include lexakai.theme
    
    title "com.telenav.kivakit.validation.lexakai"
    
    interface UmlDiagramIdentifier
    
    UmlDiagramIdentifier <|-- DiagramValidation
    class DiagramValidation
    {
    }
    
@enduml

